#!/usr/bin/env python3
"""
Generate Go proxy routes from OpenAPI specification.

This script parses an OpenAPI YAML file and generates Go code with route definitions
for the API Gateway to proxy to the Orchestrator.

Usage:
    python generate-proxy-routes.py --spec <openapi.yaml> --output <routes.go>
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install with: pip install pyyaml")
    sys.exit(1)


def load_openapi_spec(spec_path: Path) -> dict[str, Any]:
    """Load and parse OpenAPI YAML specification."""
    with open(spec_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def path_to_operation_id(method: str, path: str) -> str:
    """Generate operation ID from method and path if not provided."""
    # Remove leading/trailing slashes and split
    parts = path.strip("/").split("/")

    # Convert path parts to camelCase
    words = []
    for part in parts:
        # Skip path parameters like {id}
        if part.startswith("{") and part.endswith("}"):
            param_name = part[1:-1]
            words.append(f"By{param_name.capitalize()}")
        else:
            # Convert kebab-case to parts
            for word in part.replace("-", "_").split("_"):
                words.append(word.capitalize())

    # Add method prefix
    method_prefix = method.lower()
    if method_prefix == "get":
        method_prefix = "get"
    elif method_prefix == "post":
        method_prefix = "create"
    elif method_prefix == "put":
        method_prefix = "update"
    elif method_prefix == "patch":
        method_prefix = "patch"
    elif method_prefix == "delete":
        method_prefix = "delete"

    if words:
        return method_prefix + "".join(words)
    return method_prefix


def convert_path_params(path: str) -> str:
    """Convert OpenAPI {param} to Gin :param format."""
    return re.sub(r'\{(\w+)\}', r':\1', path)


def extract_routes(spec: dict[str, Any], api_prefix: str = "/api/v2") -> list[dict[str, str]]:
    """Extract route definitions from OpenAPI spec.

    Args:
        spec: OpenAPI specification dict
        api_prefix: Only include paths starting with this prefix, and strip it
    """
    routes = []
    paths = spec.get("paths", {})
    seen = set()  # Track duplicates

    http_methods = ["get", "post", "put", "patch", "delete", "head", "options"]

    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue

        # Filter only paths with specified prefix
        if not path.startswith(api_prefix):
            continue

        # Strip the prefix (e.g., /api/v2/templates/ -> /templates/)
        relative_path = path[len(api_prefix):]
        if not relative_path.startswith("/"):
            relative_path = "/" + relative_path

        # Convert {param} to :param for Gin
        # Keep trailing slash from Django convention (source of truth)
        gin_path = convert_path_params(relative_path)

        for method in http_methods:
            if method not in path_item:
                continue

            operation = path_item[method]
            if not isinstance(operation, dict):
                continue

            # Check for duplicates
            route_key = (method.upper(), gin_path)
            if route_key in seen:
                print(f"Warning: Duplicate route skipped: {method.upper()} {gin_path}")
                continue
            seen.add(route_key)

            # Get operationId or generate one
            operation_id = operation.get("operationId")
            if not operation_id:
                operation_id = path_to_operation_id(method, path)

            routes.append({
                "method": method.upper(),
                "path": gin_path,
                "operation_id": operation_id,
            })

    return routes


def generate_go_code(routes: list[dict[str, str]], package_name: str = "generated") -> str:
    """Generate Go code with route definitions.

    Note: RouteDefinition type is defined in types.go, not here.
    """
    lines = [
        "// Code generated from OpenAPI. DO NOT EDIT.",
        "// This file is auto-generated by generate-proxy-routes.py",
        "",
        f"package {package_name}",
        "",
        "// OrchestratorRoutes contains all routes to proxy to Django Orchestrator",
        "var OrchestratorRoutes = []RouteDefinition{",
    ]

    for route in routes:
        method = route["method"]
        path = route["path"]
        op_id = route["operation_id"]
        lines.append(f'\t{{Method: "{method}", Path: "{path}", OperationID: "{op_id}"}},')

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Go proxy routes from OpenAPI specification"
    )
    parser.add_argument(
        "--spec",
        required=True,
        help="Path to OpenAPI YAML specification file",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to output Go file",
    )
    parser.add_argument(
        "--package",
        default="generated",
        help="Go package name (default: generated)",
    )

    args = parser.parse_args()

    spec_path = Path(args.spec)
    output_path = Path(args.output)

    if not spec_path.exists():
        print(f"Error: Spec file not found: {spec_path}")
        sys.exit(1)

    # Load spec
    print(f"Loading OpenAPI spec from {spec_path}...")
    spec = load_openapi_spec(spec_path)

    # Extract routes
    routes = extract_routes(spec)
    print(f"Found {len(routes)} routes")

    # Generate Go code
    go_code = generate_go_code(routes, args.package)

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(go_code)

    print(f"Generated {output_path}")

    # Print summary
    if routes:
        print("\nRoutes generated:")
        for route in routes[:10]:  # Show first 10
            print(f"  {route['method']:6} {route['path']}")
        if len(routes) > 10:
            print(f"  ... and {len(routes) - 10} more")


if __name__ == "__main__":
    main()
