# Generated by Django 4.2.25 on 2025-11-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_context",
                    models.JSONField(
                        default=dict, help_text="Initial input data for the workflow"
                    ),
                ),
                (
                    "final_result",
                    models.JSONField(
                        blank=True, help_text="Final workflow output data", null=True
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current execution status (FSM-protected)",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "current_node_id",
                    models.CharField(
                        blank=True,
                        help_text="Currently executing node ID",
                        max_length=100,
                    ),
                ),
                (
                    "completed_nodes",
                    models.JSONField(
                        default=list, help_text="List of completed node IDs"
                    ),
                ),
                (
                    "failed_nodes",
                    models.JSONField(default=list, help_text="List of failed node IDs"),
                ),
                (
                    "node_statuses",
                    models.JSONField(
                        default=dict,
                        help_text="Map of node_id -> status (pending/running/completed/failed/skipped)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "error_node_id",
                    models.CharField(
                        blank=True,
                        help_text="Node ID where error occurred",
                        max_length=100,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenTelemetry trace ID (hex)",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "workflow_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workflow template name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Workflow description"),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        default="general",
                        help_text="Workflow category (e.g., user_management, database_ops)",
                        max_length=100,
                    ),
                ),
                (
                    "dag_structure",
                    models.JSONField(
                        help_text="DAG structure with nodes and edges (validated by Pydantic)"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Workflow configuration (timeout, retries)",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="DAG structure is valid (cycles checked)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Template is active and can be executed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number (auto-incremented)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent template if this is a new version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="templates.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Node ID from DAG structure", max_length=100
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        help_text="Human-readable node name", max_length=200
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        help_text="Node type (operation/condition/etc)", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input data for this node"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="Output data from this node", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "span_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenTelemetry span ID (hex)",
                        max_length=16,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenTelemetry trace ID (hex)",
                        max_length=32,
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_results",
                        to="templates.workflowexecution",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_step_results",
                "ordering": ["workflow_execution", "started_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="workflow_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="templates.workflowtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["is_active", "is_valid"], name="workflow_te_is_acti_026ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="workflow_te_created_65131f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "version_number"), name="unique_workflow_name_version"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstepresult",
            index=models.Index(
                fields=["workflow_execution", "node_id"],
                name="workflow_st_workflo_9cef72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstepresult",
            index=models.Index(
                fields=["status", "-started_at"], name="workflow_st_status_9cf4a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstepresult",
            index=models.Index(
                fields=["trace_id", "span_id"], name="workflow_st_trace_i_d76aa3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstepresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["completed", "failed", "skipped"])),
                fields=("workflow_execution", "node_id"),
                name="unique_completed_step_per_execution",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="workflow_ex_status_e9bd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow_template", "status"],
                name="workflow_ex_workflo_5ca7b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["trace_id"], name="workflow_ex_trace_i_be2a7b_idx"
            ),
        ),
    ]
