# Generated by Django 4.2.25 on 2025-11-23 17:45

import apps.templates.workflow.models
import django.core.serializers.json
from django.db import migrations
import django_pydantic_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_workflow_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtemplate",
            name="config",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Workflow configuration (timeout, retries)",
                schema=apps.templates.workflow.models.WorkflowConfig,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtemplate",
            name="dag_structure",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="DAG structure with nodes and edges (Pydantic-validated)",
                schema=apps.templates.workflow.models.DAGStructure,
            ),
        ),
    ]
