# Generated by Django 4.2.25 on 2025-12-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_workflowtemplate_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='operation_type',
            field=models.CharField(max_length=32),
        ),
    ]
