# Generated by Django 4.2.25 on 2025-12-04 10:50

from django.db import migrations, models


def convert_workflow_types(apps, schema_editor):
    """
    Convert existing workflow_type values to new choices.

    Maps 'general' and any unknown values to 'sequential'.
    """
    WorkflowTemplate = apps.get_model('templates', 'WorkflowTemplate')
    valid_types = {'sequential', 'conditional', 'parallel', 'complex'}

    for template in WorkflowTemplate.objects.all():
        if template.workflow_type not in valid_types:
            template.workflow_type = 'sequential'
            template.save(update_fields=['workflow_type'])


def reverse_conversion(apps, schema_editor):
    """No-op reverse migration - values are already compatible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_extend_operation_type_max_length'),
    ]

    operations = [
        # First, convert existing data to valid choices
        migrations.RunPython(convert_workflow_types, reverse_conversion),

        # Then alter the field to add choices constraint
        migrations.AlterField(
            model_name='workflowtemplate',
            name='workflow_type',
            field=models.CharField(
                choices=[
                    ('sequential', 'Sequential'),
                    ('conditional', 'Conditional'),
                    ('parallel', 'Parallel'),
                    ('complex', 'Complex')
                ],
                default='sequential',
                help_text='Workflow type: sequential, conditional, parallel, complex',
                max_length=100
            ),
        ),
    ]
