# Generated by Django 4.2.25 on 2025-12-04 18:44

import apps.templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_workflow_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='operation_type',
            field=models.CharField(max_length=32, validators=[apps.templates.models.validate_operation_type]),
        ),
    ]
