# Generated by Django 4.2.25 on 2025-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_operationtemplate_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='category',
            field=models.CharField(choices=[('ras', 'RAS Operations'), ('odata', 'OData Operations'), ('system', 'System Operations'), ('custom', 'Custom Operations')], default='custom', help_text='Category for grouping in Operations Center', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Ant Design icon name (e.g., 'PlayCircleOutlined')", max_length=50),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='input_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema for dynamic form generation in Operations Center', null=True),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Template available for Operations Center (quick actions)'),
        ),
    ]
