# Generated by Django 6.0 on 2026-01-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_add_operations_center_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtemplate',
            options={'ordering': ['name'], 'permissions': (('manage_operation_template', 'Can manage operation templates'),)},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['-created_at'], 'permissions': (('manage_workflow_template', 'Can manage workflow templates'), ('execute_workflow_template', 'Can execute workflow templates'))},
        ),
    ]
