# Generated by Django 6.0 on 2026-01-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('templates', '0008_alter_operationtemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTemplateGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_template_permissions', to='auth.group')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='templates.operationtemplate')),
            ],
            options={
                'db_table': 'templates_operation_template_group_permissions',
                'indexes': [models.Index(fields=['group', 'template'], name='otgp_group_tpl_idx'), models.Index(fields=['template', 'level'], name='otgp_tpl_level_idx')],
                'unique_together': {('group', 'template')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_permissions', to='auth.group')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='templates.workflowtemplate')),
            ],
            options={
                'db_table': 'templates_workflow_template_group_permissions',
                'indexes': [models.Index(fields=['group', 'workflow_template'], name='wtgp_group_wf_idx'), models.Index(fields=['workflow_template', 'level'], name='wtgp_wf_level_idx')],
                'unique_together': {('group', 'workflow_template')},
            },
        ),
    ]
