# Generated by Django 6.0 on 2026-01-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_operationtemplategrouppermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='templates.operationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_template_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'templates_operation_template_permissions',
                'indexes': [models.Index(fields=['user', 'template'], name='otp_user_tpl_idx'), models.Index(fields=['template', 'level'], name='otp_tpl_level_idx')],
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_permissions', to=settings.AUTH_USER_MODEL)),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='templates.workflowtemplate')),
            ],
            options={
                'db_table': 'templates_workflow_template_permissions',
                'indexes': [models.Index(fields=['user', 'workflow_template'], name='wtp_user_wf_idx'), models.Index(fields=['workflow_template', 'level'], name='wtp_wf_level_idx')],
                'unique_together': {('user', 'workflow_template')},
            },
        ),
    ]
