# Generated by Codex CLI on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0011_migrate_legacy_ibcmd_templates_to_ibcmd_cli"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Safe execution plan (masked; MUST NOT contain raw secret values)",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="bindings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Binding provenance list (MUST NOT contain raw secret values)",
            ),
        ),
    ]

