# Generated by Django 6.0 on 2026-02-08 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0012_workflow_execution_plan_and_bindings'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_scope', models.CharField(default='global', max_length=80)),
                ('executor_kind', models.CharField(choices=[('ibcmd_cli', 'IBCMD CLI'), ('designer_cli', 'Designer CLI'), ('workflow', 'Workflow')], max_length=32)),
                ('executor_payload', models.JSONField(default=dict)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operation_definitions',
                'ordering': ['tenant_scope', 'id'],
                'indexes': [models.Index(fields=['tenant_scope', 'status'], name='op_def_scope_status_idx'), models.Index(fields=['executor_kind', 'status'], name='op_def_kind_status_idx'), models.Index(fields=['fingerprint'], name='op_def_fingerprint_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_scope', 'fingerprint'), name='op_def_scope_fingerprint_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OperationExposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.CharField(choices=[('template', 'Template'), ('action_catalog', 'Action Catalog')], max_length=32)),
                ('alias', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.CharField(blank=True, default='', max_length=128)),
                ('contexts', models.JSONField(default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('capability_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('invalid', 'Invalid')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='templates.operationdefinition')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_exposures', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'operation_exposures',
                'ordering': ['surface', 'display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OperationMigrationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_issues', to='templates.operationexposure')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_migration_issues', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'operation_migration_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationexposure',
            index=models.Index(fields=['surface', 'status'], name='op_exp_surface_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operationexposure',
            index=models.Index(fields=['tenant', 'surface'], name='op_exp_tenant_surface_idx'),
        ),
        migrations.AddIndex(
            model_name='operationexposure',
            index=models.Index(fields=['capability', 'status'], name='op_exp_cap_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationexposure',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('surface', 'alias'), name='op_exp_surface_alias_global_uniq'),
        ),
        migrations.AddConstraint(
            model_name='operationexposure',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('surface', 'alias', 'tenant'), name='op_exp_surface_alias_tenant_uniq'),
        ),
        migrations.AddIndex(
            model_name='operationmigrationissue',
            index=models.Index(fields=['severity', 'created_at'], name='op_mig_sev_created_idx'),
        ),
        migrations.AddIndex(
            model_name='operationmigrationissue',
            index=models.Index(fields=['source_type', 'source_id'], name='op_mig_source_idx'),
        ),
    ]
