# Generated by Django 6.0 on 2026-02-11 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("templates", "0016_manualoperationtemplatebinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationExposurePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(10, "View"), (20, "Operate"), (30, "Manage"), (40, "Admin")],
                        default=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "exposure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="templates.operationexposure",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_exposure_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "templates_operation_exposure_permissions",
                "indexes": [
                    models.Index(fields=["user", "exposure"], name="oep_user_exp_idx"),
                    models.Index(fields=["exposure", "level"], name="oep_exp_level_idx"),
                ],
                "unique_together": {("user", "exposure")},
            },
        ),
        migrations.CreateModel(
            name="OperationExposureGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(10, "View"), (20, "Operate"), (30, "Manage"), (40, "Admin")],
                        default=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "exposure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="templates.operationexposure",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_exposure_permissions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "templates_operation_exposure_group_permissions",
                "indexes": [
                    models.Index(fields=["group", "exposure"], name="oegp_group_exp_idx"),
                    models.Index(fields=["exposure", "level"], name="oegp_exp_level_idx"),
                ],
                "unique_together": {("group", "exposure")},
            },
        ),
    ]

