# Generated by Django 6.0 on 2026-02-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0017_operationexposurepermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationTemplateGroupPermission',
        ),
        migrations.DeleteModel(
            name='OperationTemplatePermission',
        ),
    ]
