# Generated by Django 6.0 on 2026-02-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0018_alter_operationtemplategrouppermission_unique_together_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.DeleteModel(name="OperationTemplate"),
            ],
            state_operations=[],
        ),
    ]
