# Generated by Codex CLI on 2026-02-13

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_alter_tenant_options_alter_tenantmember_options_and_more"),
        ("templates", "0020_operationexposure_exposure_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_consumer",
            field=models.CharField(
                default="legacy",
                help_text="Consumer that initiated execution (e.g. pools/extensions/operations)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant context for execution isolation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_executions",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowexecution",
            constraint=models.CheckConstraint(
                condition=~Q(execution_consumer="pools") | Q(tenant__isnull=False),
                name="workflow_exec_pools_tenant_required",
            ),
        ),
    ]
