import { describe, expect, it } from 'vitest'

import {
  buildAvailableDecisionRevisions,
  buildAvailableWorkflowRevisions,
} from '../authoringReferences'

describe('authoringReferences', () => {
  it('builds reusable workflow revision options from workflow library response', () => {
    const available = buildAvailableWorkflowRevisions([
      {
        id: 'workflow-root',
        name: 'Root Workflow',
        description: 'root',
        workflow_type: 'complex',
        category: 'custom',
        is_valid: true,
        is_active: true,
        management_mode: 'user_authored',
        visibility_surface: 'workflow_library',
        read_only_reason: null,
        version_number: 1,
        parent_version: null,
        created_by: null,
        created_by_username: 'analyst',
        node_count: 0,
        execution_count: 0,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        is_system_managed: false,
      },
      {
        id: 'workflow-revision-3',
        name: 'Services Publication',
        description: 'latest',
        workflow_type: 'complex',
        category: 'custom',
        is_valid: true,
        is_active: true,
        management_mode: 'user_authored',
        visibility_surface: 'workflow_library',
        read_only_reason: null,
        version_number: 3,
        parent_version: 'workflow-root',
        created_by: null,
        created_by_username: 'analyst',
        node_count: 0,
        execution_count: 0,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        is_system_managed: false,
      },
      {
        id: 'system-runtime-projection',
        name: 'Runtime Projection',
        description: 'system',
        workflow_type: 'complex',
        category: 'system',
        is_valid: true,
        is_active: true,
        management_mode: 'system_managed',
        visibility_surface: 'runtime_diagnostics',
        read_only_reason: 'system',
        version_number: 9,
        parent_version: null,
        created_by: null,
        created_by_username: 'system',
        node_count: 0,
        execution_count: 0,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        is_system_managed: true,
      },
    ])

    expect(available).toEqual([
      {
        id: 'workflow-root',
        name: 'Root Workflow',
        workflowDefinitionKey: 'workflow-root',
        workflowRevisionId: 'workflow-root',
        workflowRevision: 1,
      },
      {
        id: 'workflow-revision-3',
        name: 'Services Publication',
        workflowDefinitionKey: 'workflow-root',
        workflowRevisionId: 'workflow-revision-3',
        workflowRevision: 3,
      },
    ])
  })

  it('builds reusable decision revision options from /decisions response', () => {
    const available = buildAvailableDecisionRevisions([
      {
        id: 'decision-compatible',
        name: 'Compatible Policy',
        decision_table_id: 'decision-root',
        decision_key: 'document_policy',
        decision_revision: 2,
        description: 'compatible',
        inputs: [],
        outputs: [],
        rules: [],
        hit_policy: 'first_match',
        validation_mode: 'fail_closed',
        is_active: true,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        metadata_context: {
          config_name: 'shared-profile',
          config_version: '8.3.24',
        },
        metadata_compatibility: {
          status: 'compatible',
          reason: null,
          is_compatible: true,
        },
      },
      {
        id: 'decision-drifted',
        name: 'Drifted Policy',
        decision_table_id: 'decision-root',
        decision_key: 'document_policy',
        decision_revision: 3,
        description: 'drifted',
        inputs: [],
        outputs: [],
        rules: [],
        hit_policy: 'first_match',
        validation_mode: 'fail_closed',
        is_active: true,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        metadata_context: {
          config_name: 'shared-profile',
          config_version: '8.3.24',
          publication_drift: true,
        },
        metadata_compatibility: {
          status: 'compatible',
          reason: 'metadata_surface_diverged',
          is_compatible: true,
        },
      },
      {
        id: 'decision-incompatible',
        name: 'Incompatible Policy',
        decision_table_id: 'decision-root',
        decision_key: 'document_policy',
        decision_revision: 4,
        description: 'incompatible',
        inputs: [],
        outputs: [],
        rules: [],
        hit_policy: 'first_match',
        validation_mode: 'fail_closed',
        is_active: true,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        metadata_context: {
          config_name: 'other-profile',
          config_version: '1.0.0',
        },
        metadata_compatibility: {
          status: 'incompatible',
          reason: 'configuration_scope_mismatch',
          is_compatible: false,
        },
      },
      {
        id: 'decision-inactive',
        name: 'Inactive Policy',
        decision_table_id: 'decision-root',
        decision_key: 'document_policy',
        decision_revision: 1,
        description: 'inactive',
        inputs: [],
        outputs: [],
        rules: [],
        hit_policy: 'first_match',
        validation_mode: 'fail_closed',
        is_active: false,
        created_at: '2026-03-08T12:00:00Z',
        updated_at: '2026-03-08T12:00:00Z',
        metadata_context: undefined,
        metadata_compatibility: undefined,
      },
    ])

    expect(available).toEqual([
      {
        id: 'decision-compatible',
        name: 'Compatible Policy',
        decisionTableId: 'decision-root',
        decisionKey: 'document_policy',
        decisionRevision: 2,
        metadataContext: {
          config_name: 'shared-profile',
          config_version: '8.3.24',
        },
        metadataCompatibility: {
          status: 'compatible',
          reason: null,
          is_compatible: true,
        },
      },
      {
        id: 'decision-drifted',
        name: 'Drifted Policy',
        decisionTableId: 'decision-root',
        decisionKey: 'document_policy',
        decisionRevision: 3,
        metadataContext: {
          config_name: 'shared-profile',
          config_version: '8.3.24',
          publication_drift: true,
        },
        metadataCompatibility: {
          status: 'compatible',
          reason: 'metadata_surface_diverged',
          is_compatible: true,
        },
      },
    ])
  })
})
