# Generated by Django 6.0 on 2026-04-19 09:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiIncidentTelemetryBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('batch_id', models.CharField(max_length=160)),
                ('flush_reason', models.CharField(max_length=32)),
                ('session_id', models.CharField(blank=True, default='', max_length=160)),
                ('release_app', models.CharField(blank=True, default='', max_length=120)),
                ('release_fingerprint', models.CharField(blank=True, default='', max_length=160)),
                ('release_mode', models.CharField(blank=True, default='', max_length=80)),
                ('release_origin', models.CharField(blank=True, default='', max_length=255)),
                ('route_path', models.CharField(blank=True, default='', max_length=255)),
                ('route_search', models.CharField(blank=True, default='', max_length=255)),
                ('route_hash', models.CharField(blank=True, default='', max_length=255)),
                ('route_context', models.JSONField(blank=True, default=dict)),
                ('accepted_event_count', models.PositiveIntegerField(default=0)),
                ('duplicate_event_count', models.PositiveIntegerField(default=0)),
                ('dropped_event_count', models.PositiveIntegerField(default=0)),
                ('first_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('last_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_incident_telemetry_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_incident_telemetry_batches', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'monitoring_ui_incident_telemetry_batches',
                'ordering': ['-last_occurred_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UiIncidentTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('session_id', models.CharField(blank=True, default='', max_length=160)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('route_path', models.CharField(blank=True, default='', max_length=255)),
                ('route_search', models.CharField(blank=True, default='', max_length=255)),
                ('route_hash', models.CharField(blank=True, default='', max_length=255)),
                ('route_context', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=160)),
                ('ui_action_id', models.CharField(blank=True, default='', max_length=160)),
                ('trace_id', models.CharField(blank=True, default='', max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_incident_telemetry_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.uiincidenttelemetrybatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_incident_telemetry_events', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'monitoring_ui_incident_telemetry_events',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetrybatch',
            index=models.Index(fields=['tenant', 'last_occurred_at'], name='uiit_batch_tenant_last_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetrybatch',
            index=models.Index(fields=['tenant', 'actor_username'], name='uiit_batch_tenant_actor_idx'),
        ),
        migrations.AddConstraint(
            model_name='uiincidenttelemetrybatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch_id'), name='uiit_batch_tenant_batch_uniq'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='uiit_event_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'session_id'], name='uiit_event_tenant_sess_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'request_id'], name='uiit_event_tenant_req_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'ui_action_id'], name='uiit_event_tenant_act_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'route_path'], name='uiit_event_tenant_route_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'actor_username'], name='uiit_event_tenant_user_idx'),
        ),
        migrations.AddIndex(
            model_name='uiincidenttelemetryevent',
            index=models.Index(fields=['tenant', 'event_type'], name='uiit_event_tenant_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='uiincidenttelemetryevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_id'), name='uiit_event_tenant_event_uniq'),
        ),
    ]
