package performance

import (
	"fmt"
	"os"
	"text/template"
	"time"
)

// PerformanceReport - отчет о performance тесте
type PerformanceReport struct {
	TestName        string        `json:"test_name"`
	Timestamp       time.Time     `json:"timestamp"`
	TotalOperations int           `json:"total_operations"`
	SuccessCount    int           `json:"success_count"`
	FailureCount    int           `json:"failure_count"`
	TotalDuration   time.Duration `json:"total_duration"`
	OpsPerSecond    float64       `json:"ops_per_second"`
	SuccessRate     float64       `json:"success_rate"` // 0.0-1.0 fraction
	LatencyMin      float64       `json:"latency_min_seconds"`
	LatencyMean     float64       `json:"latency_mean_seconds"`
	LatencyP50      float64       `json:"latency_p50_seconds"`
	LatencyP95      float64       `json:"latency_p95_seconds"`
	LatencyP99      float64       `json:"latency_p99_seconds"`
	LatencyMax      float64       `json:"latency_max_seconds"`
	Latencies       []time.Duration `json:"latencies,omitempty"`
}

// ComparisonReport - сравнение Event-Driven vs HTTP Sync
type ComparisonReport struct {
	Timestamp time.Time `json:"timestamp"`

	// Event-Driven metrics
	EventDrivenOPS float64 `json:"event_driven_ops_per_sec"`
	EventDrivenP50 float64 `json:"event_driven_p50_seconds"`
	EventDrivenP95 float64 `json:"event_driven_p95_seconds"`
	EventDrivenP99 float64 `json:"event_driven_p99_seconds"`

	// HTTP Sync metrics
	HTTPSyncOPS float64 `json:"http_sync_ops_per_sec"`
	HTTPSyncP50 float64 `json:"http_sync_p50_seconds"`
	HTTPSyncP95 float64 `json:"http_sync_p95_seconds"`
	HTTPSyncP99 float64 `json:"http_sync_p99_seconds"`

	// Improvements (Event-Driven / HTTP Sync)
	ThroughputImprovement   float64 `json:"throughput_improvement_factor"`
	LatencyP50Improvement   float64 `json:"latency_p50_improvement_factor"`
	LatencyP95Improvement   float64 `json:"latency_p95_improvement_factor"`
	LatencyP99Improvement   float64 `json:"latency_p99_improvement_factor"`
}

const reportTemplate = `# Performance Test Report

**Generated:** {{.Timestamp.Format "2006-01-02 15:04:05"}}

## Summary

| Metric | Value |
|--------|-------|
| Total Operations | {{.TotalOperations}} |
| Success Count | {{.SuccessCount}} |
| Failure Count | {{.FailureCount}} |
| Success Rate | {{printf "%.0f" (call .SuccessRatePercent)}}% |
| Total Duration | {{.TotalDuration}} |
| Operations/sec | {{printf "%.2f" .OpsPerSecond}} |

## Latency Distribution

| Percentile | Latency |
|------------|---------|
| Min | {{printf "%.3f" .LatencyMin}}s |
| Mean | {{printf "%.3f" .LatencyMean}}s |
| P50 (median) | {{printf "%.3f" .LatencyP50}}s |
| P95 | {{printf "%.3f" .LatencyP95}}s |
| P99 | {{printf "%.3f" .LatencyP99}}s |
| Max | {{printf "%.3f" .LatencyMax}}s |

## Target Validation

| Target | Expected | Actual | Status |
|--------|----------|--------|--------|
| Success Rate | > 95% | {{printf "%.0f" (call .SuccessRatePercent)}}% | {{if gt .SuccessRate 0.95}}✅ PASS{{else}}❌ FAIL{{end}} |
| P99 Latency | < 10s | {{printf "%.3f" .LatencyP99}}s | {{if lt .LatencyP99 10.0}}✅ PASS{{else}}❌ FAIL{{end}} |
| Throughput | > 10 ops/s | {{printf "%.2f" .OpsPerSecond}} ops/s | {{if gt .OpsPerSecond 10.0}}✅ PASS{{else}}❌ FAIL{{end}} |

## Conclusion

{{if and (gt .SuccessRate 0.95) (lt .LatencyP99 10.0) (gt .OpsPerSecond 10.0)}}
✅ **ALL TARGETS ACHIEVED**

The performance test successfully met all acceptance criteria:
- High reliability (success rate > 95%)
- Low latency (P99 < 10 seconds)
- Good throughput (> 10 operations/second)
{{else}}
⚠️ **SOME TARGETS NOT MET**

Performance targets that need attention:
{{if le .SuccessRate 0.95}}
- ❌ Success rate below 95% - investigate failures
{{end}}
{{if ge .LatencyP99 10.0}}
- ❌ P99 latency above 10 seconds - optimize slow paths
{{end}}
{{if le .OpsPerSecond 10.0}}
- ❌ Throughput below 10 ops/s - scale workers or optimize processing
{{end}}
{{end}}

---
*Generated by CommandCenter1C Performance Testing Suite*
`

const comparisonTemplate = `# Event-Driven vs HTTP Sync Comparison

**Generated:** {{.Timestamp.Format "2006-01-02 15:04:05"}}

## Performance Comparison

| Metric | Event-Driven | HTTP Sync | Improvement |
|--------|--------------|-----------|-------------|
| Throughput | {{printf "%.2f" .EventDrivenOPS}} ops/s | {{printf "%.2f" .HTTPSyncOPS}} ops/s | **{{printf "%.1f" .ThroughputImprovement}}x** |
| P50 Latency | {{printf "%.3f" .EventDrivenP50}}s | {{printf "%.3f" .HTTPSyncP50}}s | {{printf "%.1f" .LatencyP50Improvement}}x faster |
| P95 Latency | {{printf "%.3f" .EventDrivenP95}}s | {{printf "%.3f" .HTTPSyncP95}}s | {{printf "%.1f" .LatencyP95Improvement}}x faster |
| P99 Latency | {{printf "%.3f" .EventDrivenP99}}s | {{printf "%.3f" .HTTPSyncP99}}s | {{printf "%.1f" .LatencyP99Improvement}}x faster |

## Visualization

### Throughput Comparison
` + "```" + `
Event-Driven: {{printf "%.0f" .EventDrivenOPS}} ops/s  ████████████████████████████████████
HTTP Sync:    {{printf "%.0f" .HTTPSyncOPS}} ops/s     ███
                                          ({{printf "%.1f" .ThroughputImprovement}}x improvement)
` + "```" + `

### Latency P99 Comparison
` + "```" + `
Event-Driven: {{printf "%.3f" .EventDrivenP99}}s  ███
HTTP Sync:    {{printf "%.3f" .HTTPSyncP99}}s     ████████████████████████████████████
                                         ({{printf "%.1f" .LatencyP99Improvement}}x faster)
` + "```" + `

## Analysis

{{if ge .ThroughputImprovement 10.0}}
✅ **TARGET ACHIEVED: 10x+ Throughput Improvement**

Event-Driven architecture demonstrates exceptional performance gains:
- **{{printf "%.1f" .ThroughputImprovement}}x higher throughput** - significantly exceeds 10x target
- Non-blocking async processing enables massive parallelism
- Redis Streams provide efficient event distribution
{{else if ge .ThroughputImprovement 5.0}}
⚠️ **GOOD PERFORMANCE: 5-10x Improvement**

Event-Driven architecture shows significant gains:
- **{{printf "%.1f" .ThroughputImprovement}}x higher throughput** - approaching 10x target
- Further optimization may push closer to 10x goal
- Consider worker pool scaling and Redis tuning
{{else}}
❌ **BELOW TARGET: < 5x Improvement**

Event-Driven architecture underperforming:
- **{{printf "%.1f" .ThroughputImprovement}}x higher throughput** - below expectations
- Investigate bottlenecks: Redis latency, worker pool size, event processing overhead
- HTTP Sync baseline may be faster than expected
{{end}}

## Key Insights

### Event-Driven Advantages
- ✅ Non-blocking: operations don't wait for responses
- ✅ Scalable: easily add more workers to increase throughput
- ✅ Resilient: failures don't block other operations
- ✅ Observable: events provide natural audit trail

### HTTP Sync Limitations
- ❌ Blocking: each request waits for full response
- ❌ Connection limits: bounded by concurrent HTTP connections
- ❌ Cascading failures: one slow service blocks caller
- ❌ Harder to scale: requires load balancers and connection pooling

## Recommendations

{{if ge .ThroughputImprovement 10.0}}
- ✅ Event-Driven architecture validated for production
- Consider further optimizations for even better performance
- Monitor performance metrics in production environment
{{else}}
- ⚠️ Review implementation for optimization opportunities
- Check Redis configuration (max connections, memory limits)
- Verify worker pool sizing matches workload
- Profile event processing to find hotspots
{{end}}

---
*Generated by CommandCenter1C Performance Testing Suite*
`

// GenerateMarkdownReport - генерирует markdown отчет из PerformanceReport
func GenerateMarkdownReport(report *PerformanceReport, filename string) error {
	// Create template with custom functions
	funcMap := template.FuncMap{
		"SuccessRatePercent": func() float64 {
			return report.SuccessRate * 100.0
		},
	}

	tmpl, err := template.New("report").Funcs(funcMap).Parse(reportTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, report); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

// GenerateComparisonReport - генерирует markdown отчет сравнения
func GenerateComparisonReport(comparison *ComparisonReport, filename string) error {
	tmpl, err := template.New("comparison").Parse(comparisonTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, comparison); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}
