from __future__ import annotations

from typing import Any

from .common import _CREDENTIAL_SEMANTICS


def _ibcmd_driver_schema_fallback() -> dict[str, Any]:
    return {
        "connection": {
            "remote": {
                "kind": "flag",
                "flag": "--remote",
                "expects_value": True,
                "required": False,
                "label": "Remote",
                "description": "Remote agent URL (optional).",
                "value_type": "string",
            },
            "pid": {
                "kind": "flag",
                "flag": "--pid",
                "expects_value": True,
                "required": False,
                "label": "PID",
                "description": "Attach to an existing ibcmd process (optional).",
                "value_type": "int",
            },
            "offline": {
                "config": {
                    "kind": "flag",
                    "flag": "--config",
                    "expects_value": True,
                    "required": False,
                    "label": "Config",
                    "description": "Offline connection: path to configuration file (optional).",
                    "value_type": "string",
                },
                "data": {
                    "kind": "flag",
                    "flag": "--data",
                    "expects_value": True,
                    "required": False,
                    "label": "Data",
                    "description": "Offline connection: path to data directory (optional).",
                    "value_type": "string",
                },
                "dbms": {
                    "kind": "flag",
                    "flag": "--dbms",
                    "expects_value": True,
                    "required": False,
                    "label": "DBMS",
                    "description": "Offline connection: DBMS kind (optional).",
                    "value_type": "string",
                },
                "db_server": {
                    "kind": "flag",
                    "flag": "--db-server",
                    "expects_value": True,
                    "required": False,
                    "label": "DB server",
                    "description": "Offline connection: database server name (optional).",
                    "value_type": "string",
                },
                "db_name": {
                    "kind": "flag",
                    "flag": "--db-name",
                    "expects_value": True,
                    "required": False,
                    "label": "DB name",
                    "description": "Offline connection: database name (optional).",
                    "value_type": "string",
                },
                "db_user": {
                    "kind": "flag",
                    "flag": "--db-user",
                    "expects_value": True,
                    "required": False,
                    "label": "DB user",
                    "description": "Offline connection: database username (optional).",
                    "value_type": "string",
                    "semantics": _CREDENTIAL_SEMANTICS["db_user"],
                },
                "db_pwd": {
                    "kind": "flag",
                    "flag": "--db-pwd",
                    "expects_value": True,
                    "required": False,
                    "label": "DB password",
                    "description": "Offline connection: database password (optional).",
                    "sensitive": True,
                    "value_type": "string",
                    "semantics": _CREDENTIAL_SEMANTICS["db_pwd"],
                },
            },
        },
        "ib_auth": {
            "strategy": {
                "kind": "enum",
                "required": False,
                "default": "actor",
                "enum": ["actor", "service", "none"],
                "label": "IB auth strategy",
                "description": "How to authenticate in the infobase: actor (per-user mapping), service (service account), or none.",
            },
            "user": {
                "kind": "flag",
                "flag": "--user",
                "expects_value": True,
                "required": False,
                "label": "IB user",
                "description": "Infobase user for ibcmd operations (optional).",
                "value_type": "string",
                "semantics": _CREDENTIAL_SEMANTICS["user"],
                "ui": {"aliases": ["-u"]},
            },
            "password": {
                "kind": "flag",
                "flag": "--password",
                "expects_value": True,
                "required": False,
                "label": "IB password",
                "description": "Infobase password for ibcmd operations (optional).",
                "value_type": "string",
                "sensitive": True,
                "semantics": _CREDENTIAL_SEMANTICS["password"],
                "ui": {"aliases": ["-P"]},
            },
        },
        "dbms_auth": {
            "strategy": {
                "kind": "enum",
                "required": False,
                "default": "actor",
                "enum": ["actor", "service"],
                "label": "DBMS auth strategy",
                "description": "How to resolve DBMS credentials for offline connection: actor (per-user mapping) or service (service account).",
            },
        },
        "timeout_seconds": {
            "kind": "int",
            "required": False,
            "default": 900,
            "min": 1,
            "max": 3600,
            "label": "Timeout (seconds)",
            "description": "Maximum execution time for this command.",
        },
        "stdin": {
            "kind": "text",
            "required": False,
            "label": "Stdin (optional)",
            "description": "Optional stdin payload for ibcmd (use with caution).",
            "ui": {"widget": "textarea", "rows": 4},
        },
        "auth_database_id": {
            "kind": "database_ref",
            "required": False,
            "label": "Auth mapping infobase",
            "description": "Used for RBAC and infobase user mapping. Not an execution target.",
            "ui": {"source": "selected_targets", "required_when": {"command_scope": "global"}},
        },
        "ui": {
            "version": 1,
            "sections": [
                {
                    "id": "ibcmd.auth",
                    "title": "Auth context",
                    "paths": ["auth_database_id", "ib_auth.strategy", "ib_auth.user", "ib_auth.password"],
                    "when": {"command_scope": "global"},
                },
                {
                    "id": "ibcmd.connection",
                    "title": "Connection",
                    "paths": [
                        "dbms_auth.strategy",
                        "connection.remote",
                        "connection.pid",
                        "connection.offline.config",
                        "connection.offline.data",
                        "connection.offline.dbms",
                        "connection.offline.db_server",
                        "connection.offline.db_name",
                        "connection.offline.db_user",
                        "connection.offline.db_pwd",
                    ],
                },
                {
                    "id": "ibcmd.execution",
                    "title": "Execution",
                    "paths": ["timeout_seconds", "stdin"],
                },
            ],
        },
    }

