# Generated by ChatGPT on 2026-01-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("member", "Member"), ("admin", "Admin")], default="member", max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="members", to="tenancy.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "tenant_members",
                "unique_together": {("tenant", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserTenantPreference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tenancy.tenant")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_pref", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "user_tenant_preferences",
            },
        ),
    ]
