# Generated by ChatGPT on 2026-01-30

from django.conf import settings
from django.db import migrations


def _seed_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    TenantMember = apps.get_model("tenancy", "TenantMember")
    UserTenantPreference = apps.get_model("tenancy", "UserTenantPreference")

    default_tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={"name": "Default"},
    )

    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    for user in User.objects.all().iterator():
        role = TenantMember.ROLE_ADMIN if getattr(user, "is_staff", False) else TenantMember.ROLE_MEMBER
        TenantMember.objects.get_or_create(
            tenant=default_tenant,
            user=user,
            defaults={"role": role},
        )
        pref, _ = UserTenantPreference.objects.get_or_create(user=user)
        if pref.active_tenant_id is None:
            pref.active_tenant = default_tenant
            pref.save(update_fields=["active_tenant", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_seed_default_tenant, reverse_code=migrations.RunPython.noop),
    ]

