# Generated by Django 6.0 on 2026-01-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_default_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantmember',
            options={'verbose_name': 'Tenant Member', 'verbose_name_plural': 'Tenant Members'},
        ),
        migrations.AlterModelOptions(
            name='usertenantpreference',
            options={'verbose_name': 'User Tenant Preference', 'verbose_name_plural': 'User Tenant Preferences'},
        ),
    ]
