# Generated by Django 4.2.25 on 2025-12-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifact_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='artifact',
            new_name='artifacts_a_kind_e85de3_idx',
            old_name='artifacts_a_kind_68a1d8_idx',
        ),
        migrations.RenameIndex(
            model_name='artifactalias',
            new_name='artifacts_a_artifac_8b16df_idx',
            old_name='artifacts_a_artifac_61cbb0_idx',
        ),
        migrations.RenameIndex(
            model_name='artifactusage',
            new_name='artifacts_a_artifac_ba629d_idx',
            old_name='artifacts_a_artifac_9ea109_idx',
        ),
        migrations.RenameIndex(
            model_name='artifactversion',
            new_name='artifacts_a_storage_7aed30_idx',
            old_name='artifacts_a_storage_8f3b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='artifactversion',
            new_name='artifacts_a_artifac_561c4b_idx',
            old_name='artifacts_a_artifac_6fd42b_idx',
        ),
    ]
