# Generated by Django 6.0 on 2026-01-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_add_config_cf_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['-created_at'], 'permissions': (('manage_artifact', 'Can manage artifacts'),)},
        ),
        migrations.AlterModelOptions(
            name='artifactversion',
            options={'ordering': ['-created_at'], 'permissions': (('upload_artifact_version', 'Can upload artifact versions'), ('download_artifact_version', 'Can download artifact versions'))},
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('extension', 'Extension'), ('config_cf', 'Config CF'), ('config_xml', 'Config XML'), ('dt_backup', 'DT Backup'), ('epf', 'EPF'), ('erf', 'ERF'), ('ibcmd_package', 'IBCMD Package'), ('driver_catalog', 'Driver Catalog'), ('ras_script', 'RAS Script'), ('other', 'Other')], max_length=64),
        ),
    ]
