# Generated by Django 6.0 on 2026-01-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_artifactgrouppermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='artifacts.artifact')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifacts_artifact_permissions',
                'indexes': [models.Index(fields=['user', 'artifact'], name='ap_user_art_idx'), models.Index(fields=['artifact', 'level'], name='ap_art_level_idx')],
                'unique_together': {('user', 'artifact')},
            },
        ),
    ]
