# Generated by Django 6.0 on 2026-01-14 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0008_artifactpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="purge_state",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("scheduled", "Scheduled"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="purge_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["is_deleted", "purge_after"], name="art_isdel_purgeafter_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["purge_state", "purge_after"], name="art_purgestate_purgeafter_idx"),
        ),
        migrations.CreateModel(
            name="ArtifactPurgeJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artifact_id", models.UUIDField(db_index=True)),
                ("mode", models.CharField(choices=[("manual", "Manual"), ("ttl", "TTL")], max_length=16)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("success", "Success"), ("failed", "Failed")], max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_objects", models.IntegerField(default=0)),
                ("deleted_objects", models.IntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("deleted_bytes", models.BigIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifact_purge_jobs_requested", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["artifact_id", "status"], name="apj_art_status_idx"),
                    models.Index(fields=["status", "created_at"], name="apj_status_created_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="artifactpurgejob",
            constraint=models.UniqueConstraint(condition=models.Q(status__in=["queued", "running"]), fields=("artifact_id",), name="apj_unique_active_artifact"),
        ),
    ]
