# Generated by Django 6.0 on 2026-01-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_artifact_purge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['-created_at'], 'permissions': (('manage_artifact', 'Can manage artifacts'), ('purge_artifact', 'Can purge artifacts'))},
        ),
    ]
