# Generated by Django 6.0 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0010_artifact_purge_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="purge_state",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("scheduled", "Scheduled"),
                    ("blocked", "Blocked"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="purge_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="purge_blockers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["purge_blocked_until"], name="art_purgeblockeduntil_idx"),
        ),
    ]
