# Generated by Django 6.0 on 2026-01-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0011_artifact_purge_blocked"),
        ("templates", "0011_migrate_legacy_ibcmd_templates_to_ibcmd_cli"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactusage",
            name="workflow_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artifact_usage",
                to="templates.workflowexecution",
            ),
        ),
        migrations.AlterField(
            model_name="artifactusage",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage",
                to="artifacts.artifactversion",
            ),
        ),
        migrations.AddIndex(
            model_name="artifactusage",
            index=models.Index(fields=["artifact", "operation"], name="artusage_art_op_idx"),
        ),
        migrations.AddIndex(
            model_name="artifactusage",
            index=models.Index(fields=["artifact", "workflow_execution"], name="artusage_art_wf_idx"),
        ),
    ]

