/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Class-aware request budgets для authenticated `/api/v2` traffic
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */
import type { GetTracingGetTracesParams, JaegerTracesResponse } from "./model";

import { customInstance } from "../mutator";
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCommandCenter1CAPIGateway = () => {
  /**
   * Proxies to Jaeger API (`/api/traces`) via API Gateway. Returns Jaeger-compatible response.
   * @summary Search traces (Jaeger proxy)
   */
  const getTracingGetTraces = (
    params: GetTracingGetTracesParams,
    options?: SecondParameter<typeof customInstance<JaegerTracesResponse>>,
  ) => {
    return customInstance<JaegerTracesResponse>(
      { url: `/api/v2/tracing/traces`, method: "GET", params },
      options,
    );
  };

  /**
   * Proxies to Jaeger API (`/api/traces/{traceId}`) via API Gateway.
   * @summary Get trace by ID (Jaeger proxy)
   */
  const getTracingGetTrace = (
    traceId: string,
    options?: SecondParameter<typeof customInstance<JaegerTracesResponse>>,
  ) => {
    return customInstance<JaegerTracesResponse>(
      { url: `/api/v2/tracing/traces/${traceId}`, method: "GET" },
      options,
    );
  };

  return { getTracingGetTraces, getTracingGetTrace };
};
export type GetTracingGetTracesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCommandCenter1CAPIGateway>["getTracingGetTraces"]
    >
  >
>;
export type GetTracingGetTraceResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCommandCenter1CAPIGateway>["getTracingGetTrace"]
    >
  >
>;
