export const poolMasterDataRegistryResponse = {
  contract_version: 'pool_master_data_registry.v1',
  count: 4,
  entries: [
    {
      entity_type: 'party',
      label: 'Party',
      kind: 'canonical',
      display_order: 10,
      binding_scope_fields: ['canonical_id', 'database_id', 'ib_catalog_kind'],
      capabilities: {
        direct_binding: true,
        token_exposure: true,
        bootstrap_import: true,
        outbox_fanout: true,
        sync_outbound: true,
        sync_inbound: true,
        sync_reconcile: true,
      },
      token_contract: {
        enabled: true,
        qualifier_kind: 'ib_catalog_kind',
        qualifier_required: true,
        qualifier_options: ['organization', 'counterparty'],
      },
      bootstrap_contract: { enabled: true, dependency_order: 10 },
      runtime_consumers: ['bindings', 'bootstrap_import', 'sync', 'token_catalog', 'token_parser'],
    },
    {
      entity_type: 'item',
      label: 'Item',
      kind: 'canonical',
      display_order: 20,
      binding_scope_fields: ['canonical_id', 'database_id'],
      capabilities: {
        direct_binding: true,
        token_exposure: true,
        bootstrap_import: true,
        outbox_fanout: true,
        sync_outbound: true,
        sync_inbound: true,
        sync_reconcile: true,
      },
      token_contract: {
        enabled: true,
        qualifier_kind: 'none',
        qualifier_required: false,
        qualifier_options: [],
      },
      bootstrap_contract: { enabled: true, dependency_order: 20 },
      runtime_consumers: ['bindings', 'bootstrap_import', 'sync', 'token_catalog', 'token_parser'],
    },
    {
      entity_type: 'contract',
      label: 'Contract',
      kind: 'canonical',
      display_order: 30,
      binding_scope_fields: ['canonical_id', 'database_id', 'owner_counterparty_canonical_id'],
      capabilities: {
        direct_binding: true,
        token_exposure: true,
        bootstrap_import: true,
        outbox_fanout: true,
        sync_outbound: true,
        sync_inbound: true,
        sync_reconcile: true,
      },
      token_contract: {
        enabled: true,
        qualifier_kind: 'owner_counterparty_canonical_id',
        qualifier_required: true,
        qualifier_options: [],
      },
      bootstrap_contract: { enabled: true, dependency_order: 30 },
      runtime_consumers: ['bindings', 'bootstrap_import', 'sync', 'token_catalog', 'token_parser'],
    },
    {
      entity_type: 'tax_profile',
      label: 'Tax Profile',
      kind: 'canonical',
      display_order: 40,
      binding_scope_fields: ['canonical_id', 'database_id'],
      capabilities: {
        direct_binding: true,
        token_exposure: true,
        bootstrap_import: true,
        outbox_fanout: true,
        sync_outbound: true,
        sync_inbound: true,
        sync_reconcile: true,
      },
      token_contract: {
        enabled: true,
        qualifier_kind: 'none',
        qualifier_required: false,
        qualifier_options: [],
      },
      bootstrap_contract: { enabled: true, dependency_order: 40 },
      runtime_consumers: ['bindings', 'bootstrap_import', 'sync', 'token_catalog', 'token_parser'],
    },
  ],
} as const
