# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMappingSpec",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_kind", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], db_index=True, default="draft", max_length=16)),
                ("spec", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mapping_specs", to="tenancy.tenant")),
            ],
            options={
                "db_table": "tenant_mapping_specs",
                "unique_together": {("tenant", "entity_kind", "status")},
            },
        ),
        migrations.AddIndex(
            model_name="tenantmappingspec",
            index=models.Index(fields=["tenant", "entity_kind", "status"], name="tenant_map_tenant__8b89b4_idx"),
        ),
    ]

