# Generated by Django 6.0 on 2026-01-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantmappingspec',
            new_name='tenant_mapp_tenant__71e2df_idx',
            old_name='tenant_map_tenant__8b89b4_idx',
        ),
    ]
