// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/block-sessions": {
            "post": {
                "description": "Prevent users from starting new sessions during maintenance window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Block sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Block parameters",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.BlockSessionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/create-infobase": {
            "post": {
                "description": "Create new 1C infobase in cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Create infobase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Infobase details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.CreateInfobaseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.CreateInfobaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/drop-infobase": {
            "post": {
                "description": "Delete infobase and optionally drop associated database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Drop infobase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Drop parameters",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.DropInfobaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-cluster": {
            "get": {
                "description": "Get specific cluster by UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "Get cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RAS server address (host:port)",
                        "name": "server",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ClusterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-infobase": {
            "get": {
                "description": "Get specific infobase details by UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Get infobase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.InfobaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/list-clusters": {
            "get": {
                "description": "Get list of all 1C clusters from RAS server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "List clusters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RAS server address (host:port)",
                        "name": "server",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ClustersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/list-infobases": {
            "get": {
                "description": "Get list of all infobases in cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "List infobases",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.InfobasesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/list-sessions": {
            "get": {
                "description": "Get list of all user sessions on infobase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SessionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lock-infobase": {
            "post": {
                "description": "Lock infobase to block scheduled jobs execution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Lock infobase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Database credentials",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.LockInfobaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/terminate-session": {
            "post": {
                "description": "Terminate specific user session (NOT IMPLEMENTED - service layer support needed)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Terminate session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.TerminateSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/terminate-sessions": {
            "post": {
                "description": "Terminate all or specific user sessions on infobase (selective termination not yet implemented)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Terminate sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Session IDs to terminate (optional)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.TerminateSessionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.TerminateSessionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/unblock-sessions": {
            "post": {
                "description": "Allow users to start new sessions after maintenance window",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Unblock sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Database credentials",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.UnblockSessionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/unlock-infobase": {
            "post": {
                "description": "Unlock infobase to enable scheduled jobs execution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Infobases"
                ],
                "summary": "Unlock infobase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Infobase UUID",
                        "name": "infobase_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Database credentials",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.UnlockInfobaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_rest_v2.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Cluster": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Infobase": {
            "type": "object",
            "properties": {
                "db_name": {
                    "type": "string"
                },
                "db_pwd": {
                    "type": "string"
                },
                "db_server": {
                    "type": "string"
                },
                "db_user": {
                    "description": "Database credentials (for create/update operations)",
                    "type": "string"
                },
                "dbms": {
                    "type": "string"
                },
                "denied_from": {
                    "description": "Week 4.6: Sessions block parameters",
                    "type": "string"
                },
                "denied_message": {
                    "type": "string"
                },
                "denied_parameter": {
                    "type": "string"
                },
                "denied_to": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission_code": {
                    "type": "string"
                },
                "scheduled_jobs_deny": {
                    "description": "Week 2: Lock/Unlock fields",
                    "type": "boolean"
                },
                "sessions_deny": {
                    "description": "Блокировка пользователей",
                    "type": "boolean"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Session": {
            "type": "object",
            "properties": {
                "application": {
                    "type": "string"
                },
                "session_id": {
                    "description": "Legacy alias for UUID",
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "uuid": {
                    "description": "RAS internal UUID",
                    "type": "string"
                }
            }
        },
        "internal_api_rest_v2.BlockSessionsRequest": {
            "type": "object",
            "properties": {
                "db_password": {
                    "type": "string",
                    "example": "password"
                },
                "db_user": {
                    "type": "string",
                    "example": "admin"
                },
                "denied_from": {
                    "type": "string",
                    "example": "2025-11-23T12:00:00Z"
                },
                "denied_message": {
                    "type": "string",
                    "example": "Database maintenance in progress"
                },
                "denied_to": {
                    "type": "string",
                    "example": "2025-11-23T18:00:00Z"
                },
                "parameter": {
                    "type": "string",
                    "example": "scheduled_maintenance"
                },
                "permission_code": {
                    "type": "string",
                    "example": "MaintenanceMode"
                }
            }
        },
        "internal_api_rest_v2.ClusterResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Cluster"
                }
            }
        },
        "internal_api_rest_v2.ClustersResponse": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Cluster"
                    }
                },
                "count": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_api_rest_v2.CreateInfobaseRequest": {
            "type": "object",
            "required": [
                "db_name",
                "dbms",
                "name"
            ],
            "properties": {
                "date_offset": {
                    "type": "integer",
                    "example": 2000
                },
                "db_name": {
                    "type": "string",
                    "example": "testdb"
                },
                "db_password": {
                    "type": "string",
                    "example": "password"
                },
                "db_server_name": {
                    "type": "string",
                    "example": "localhost"
                },
                "db_user": {
                    "type": "string",
                    "example": "sa"
                },
                "dbms": {
                    "type": "string",
                    "example": "MSSQLServer"
                },
                "description": {
                    "type": "string",
                    "example": "Test database for development"
                },
                "license_distribution": {
                    "type": "boolean",
                    "example": true
                },
                "locale": {
                    "type": "string",
                    "example": "ru_RU"
                },
                "name": {
                    "type": "string",
                    "example": "TestDatabase"
                },
                "scheduled_jobs_denied": {
                    "type": "boolean",
                    "example": false
                },
                "sessions_denied": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_api_rest_v2.CreateInfobaseResponse": {
            "type": "object",
            "properties": {
                "infobase_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "message": {
                    "type": "string",
                    "example": "Infobase created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_rest_v2.DropInfobaseRequest": {
            "type": "object",
            "properties": {
                "drop_database": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_rest_v2.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "MISSING_PARAMETER"
                },
                "details": {
                    "type": "string",
                    "example": "validation failed"
                },
                "error": {
                    "type": "string",
                    "example": "cluster_id is required"
                }
            }
        },
        "internal_api_rest_v2.InfobaseResponse": {
            "type": "object",
            "properties": {
                "infobase": {
                    "$ref": "#/definitions/github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Infobase"
                }
            }
        },
        "internal_api_rest_v2.InfobasesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "infobases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Infobase"
                    }
                }
            }
        },
        "internal_api_rest_v2.LockInfobaseRequest": {
            "type": "object",
            "properties": {
                "db_password": {
                    "type": "string",
                    "example": "password"
                },
                "db_user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_api_rest_v2.SessionsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 10
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_commandcenter1c_commandcenter_ras-adapter_internal_models.Session"
                    }
                }
            }
        },
        "internal_api_rest_v2.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_rest_v2.TerminateSessionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Session terminated successfully"
                },
                "session_id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_api_rest_v2.TerminateSessionsRequest": {
            "type": "object",
            "required": [
                "session_ids"
            ],
            "properties": {
                "session_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        "f9e8d7c6-b5a4-3210-9876-543210fedcba"
                    ]
                }
            }
        },
        "internal_api_rest_v2.TerminateSessionsResponse": {
            "type": "object",
            "properties": {
                "failed_count": {
                    "type": "integer",
                    "example": 2
                },
                "failed_sessions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "session-1",
                        "session-2"
                    ]
                },
                "terminated_count": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "internal_api_rest_v2.UnblockSessionsRequest": {
            "type": "object",
            "properties": {
                "db_password": {
                    "type": "string",
                    "example": "password"
                },
                "db_user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_api_rest_v2.UnlockInfobaseRequest": {
            "type": "object",
            "properties": {
                "db_password": {
                    "type": "string",
                    "example": "password"
                },
                "db_user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
