"""UI table metadata part."""

from __future__ import annotations

TABLE_METADATA_PART = {
    "operations": {
        "table_id": "operations",
        "version": "2025-12-30",
        "columns": [
            {
                "key": "name",
                "label": "Name",
                "group_key": "core",
                "group_label": "Core",
                "sortable": True,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["contains", "eq"], "placeholder": "Name"},
                "server_field": "name",
            },
            {
                "key": "id",
                "label": "Operation ID",
                "group_key": "core",
                "group_label": "Core",
                "sortable": False,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["eq"], "placeholder": "Operation ID"},
                "server_field": "id",
            },
            {
                "key": "workflow_execution_id",
                "label": "Workflow",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": False,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["contains", "eq"], "placeholder": "Workflow ID"},
                "server_field": "workflow_execution_id",
            },
            {
                "key": "operation_type",
                "label": "Type",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": True,
                "data_type": "enum",
                "filter": {
                    "type": "select",
                    "operators": ["eq", "in"],
                    "options": [
                        {"value": "designer_cli", "label": "designer_cli"},
                        {"value": "lock_scheduled_jobs", "label": "lock_scheduled_jobs"},
                        {"value": "unlock_scheduled_jobs", "label": "unlock_scheduled_jobs"},
                        {"value": "terminate_sessions", "label": "terminate_sessions"},
                        {"value": "block_sessions", "label": "block_sessions"},
                        {"value": "unblock_sessions", "label": "unblock_sessions"},
                        {"value": "query", "label": "query"},
                        {"value": "sync_cluster", "label": "sync_cluster"},
                        {"value": "health_check", "label": "health_check"},
                    ],
                },
                "server_field": "operation_type",
            },
            {
                "key": "status",
                "label": "Status",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": True,
                "data_type": "enum",
                "filter": {
                    "type": "select",
                    "operators": ["eq", "in"],
                    "options": [
                        {"value": "pending", "label": "pending"},
                        {"value": "queued", "label": "queued"},
                        {"value": "processing", "label": "processing"},
                        {"value": "completed", "label": "completed"},
                        {"value": "failed", "label": "failed"},
                        {"value": "cancelled", "label": "cancelled"},
                    ],
                },
                "server_field": "status",
            },
            {
                "key": "progress",
                "label": "Progress",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": False,
                "data_type": "number",
            },
            {
                "key": "databases",
                "label": "Databases",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": False,
                "data_type": "text",
            },
            {
                "key": "created_at",
                "label": "Created",
                "group_key": "time",
                "group_label": "Time",
                "sortable": True,
                "data_type": "datetime",
                "filter": {"type": "date", "operators": ["eq", "before", "after"], "placeholder": "Created at"},
                "server_field": "created_at",
            },
            {
                "key": "duration_seconds",
                "label": "Duration",
                "group_key": "time",
                "group_label": "Time",
                "sortable": True,
                "data_type": "number",
                "filter": {"type": "number", "operators": ["eq", "gt", "lt"], "placeholder": "Duration (s)"},
                "server_field": "duration_seconds",
            },
            {
                "key": "actions",
                "label": "Actions",
                "group_key": "actions",
                "group_label": "Actions",
                "sortable": False,
                "data_type": "action",
            },
        ],
    },
}
