"""UI table metadata part."""

from __future__ import annotations

TABLE_METADATA_PART = {
    "operation_tasks": {
        "table_id": "operation_tasks",
        "version": "2025-12-30",
        "columns": [
            {
                "key": "database_name",
                "label": "Database",
                "group_key": "core",
                "group_label": "Core",
                "sortable": True,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["contains", "eq"], "placeholder": "Database"},
                "server_field": "database_name",
            },
            {
                "key": "status",
                "label": "Status",
                "group_key": "status",
                "group_label": "Status",
                "sortable": True,
                "data_type": "enum",
                "filter": {
                    "type": "select",
                    "operators": ["eq", "in"],
                    "options": [
                        {"value": "pending", "label": "pending"},
                        {"value": "queued", "label": "queued"},
                        {"value": "processing", "label": "processing"},
                        {"value": "completed", "label": "completed"},
                        {"value": "failed", "label": "failed"},
                        {"value": "retry", "label": "retry"},
                        {"value": "cancelled", "label": "cancelled"},
                    ],
                },
                "server_field": "status",
            },
            {
                "key": "started_at",
                "label": "Started",
                "group_key": "time",
                "group_label": "Time",
                "sortable": True,
                "data_type": "datetime",
                "filter": {"type": "date", "operators": ["eq", "before", "after"], "placeholder": "Started at"},
                "server_field": "started_at",
            },
            {
                "key": "completed_at",
                "label": "Completed",
                "group_key": "time",
                "group_label": "Time",
                "sortable": True,
                "data_type": "datetime",
                "filter": {"type": "date", "operators": ["eq", "before", "after"], "placeholder": "Completed at"},
                "server_field": "completed_at",
            },
            {
                "key": "duration_seconds",
                "label": "Duration",
                "group_key": "time",
                "group_label": "Time",
                "sortable": True,
                "data_type": "number",
                "filter": {"type": "number", "operators": ["eq", "gt", "lt"], "placeholder": "Duration (s)"},
                "server_field": "duration_seconds",
            },
            {
                "key": "worker_id",
                "label": "Worker",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": True,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["contains", "eq"], "placeholder": "Worker ID"},
                "server_field": "worker_id",
            },
            {
                "key": "error_message",
                "label": "Error",
                "group_key": "meta",
                "group_label": "Meta",
                "sortable": False,
                "data_type": "text",
                "filter": {"type": "text", "operators": ["contains", "eq"], "placeholder": "Error message"},
                "server_field": "error_message",
            },
        ],
    },
}
