/**
 * System API Adapter.
 *
 * Bridges the gap between the old endpoint-based API and the new
 * generated API from OpenAPI specifications.
 *
 * This adapter:
 * 1. Uses customInstance (same as generated code) for API calls
 * 2. Provides the same function signatures as endpoints/system.ts
 * 3. Maps to the v2 action-based endpoints
 *
 * Note: SystemHealth types are not generated by OpenAPI, so we define
 * them locally (matching the legacy types for backward compatibility).
 */

import { customInstance } from '../mutator'

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * Individual service health status.
 */
export interface ServiceHealth {
  name: string
  type: string
  url?: string
  status: 'online' | 'offline' | 'degraded'
  response_time_ms: number | null
  last_check: string
  details?: Record<string, unknown>
}

/**
 * Aggregated health statistics.
 */
export interface SystemHealthStatistics {
  total: number
  online: number
  offline: number
  degraded: number
}

/**
 * Complete system health response.
 */
export interface SystemHealthResponse {
  timestamp: string
  overall_status: 'healthy' | 'degraded' | 'critical'
  services: ServiceHealth[]
  statistics: SystemHealthStatistics
}

// ============================================================================
// System Health Endpoints
// ============================================================================

/**
 * Get system health status for all monitored services.
 *
 * Returns comprehensive system health status with parallel service checks.
 * Response includes individual service statuses and aggregated statistics.
 */
export const getSystemHealth = async (): Promise<SystemHealthResponse> => {
  return customInstance<SystemHealthResponse>({
    url: '/api/v2/system/health/',
    method: 'GET',
  })
}

// ============================================================================
// Exported API Object (for backward compatibility)
// ============================================================================

/**
 * System API object with all available methods.
 * Matches the structure from endpoints/system.ts for drop-in replacement.
 */
export const systemApi = {
  getHealth: getSystemHealth,
}

export default systemApi
