# Generated by Django 4.2.7 on 2025-10-20 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("databases", "0001_initial"),
        ("templates", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchOperation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("query", "Query"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "target_entity",
                    models.CharField(
                        help_text="1C entity name (e.g., Справочник_Пользователи)",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Operation payload/parameters"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Execution configuration (timeout, retries, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "total_tasks",
                    models.IntegerField(default=0, help_text="Total number of tasks"),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(
                        default=0, help_text="Number of completed tasks"
                    ),
                ),
                (
                    "failed_tasks",
                    models.IntegerField(default=0, help_text="Number of failed tasks"),
                ),
                (
                    "retry_tasks",
                    models.IntegerField(
                        default=0, help_text="Number of tasks in retry"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User who created operation",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_databases",
                    models.ManyToManyField(
                        help_text="Databases to execute operation on",
                        related_name="batch_operations",
                        to="databases.database",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_operations",
                        to="templates.operationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Operation",
                "verbose_name_plural": "Batch Operations",
                "db_table": "batch_operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True,
                        help_text="Worker that processed this task",
                        max_length=255,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Task result data", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, help_text="Error code if failed", max_length=50
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Task duration in seconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="operations.batchoperation",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="databases.database",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch_operation", "status"],
                        name="tasks_batch_o_248406_idx",
                    ),
                    models.Index(
                        fields=["database", "status"], name="tasks_databas_7245b9_idx"
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="tasks_status_2fbca9_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="tasks_celery__c69876_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tasks_created_db4e37_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="batchoperation",
            index=models.Index(
                fields=["status", "created_at"], name="batch_opera_status_b9126c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchoperation",
            index=models.Index(
                fields=["operation_type", "status"],
                name="batch_opera_operati_b4a3e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batchoperation",
            index=models.Index(
                fields=["celery_task_id"], name="batch_opera_celery__b92516_idx"
            ),
        ),
    ]
