# Generated by Django 4.2.9 on 2025-11-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("query", "Query"),
                    ("install_extension", "Install Extension"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
