# Generated by Django 4.2.25 on 2025-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_add_failed_event_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensationAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operation_id", models.CharField(db_index=True, max_length=64)),
                ("compensation_name", models.CharField(max_length=100)),
                ("success", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=1)),
                ("duration_seconds", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Compensation Audit Log",
                "verbose_name_plural": "Compensation Audit Logs",
                "db_table": "compensation_audit_logs",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="failedevent",
            new_name="failed_even_status_902e34_idx",
            old_name="failed_even_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="failedevent",
            new_name="failed_even_correla_7ebbba_idx",
            old_name="failed_even_correl_idx",
        ),
        migrations.RenameIndex(
            model_name="failedevent",
            new_name="failed_even_channel_02aa39_idx",
            old_name="failed_even_channel_status_idx",
        ),
        migrations.AddIndex(
            model_name="compensationauditlog",
            index=models.Index(
                fields=["operation_id", "executed_at"],
                name="compensatio_operati_ac1628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compensationauditlog",
            index=models.Index(
                fields=["success", "executed_at"], name="compensatio_success_7692d8_idx"
            ),
        ),
    ]
