# Generated by Django 4.2.25 on 2025-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_compensationauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchoperation',
            name='operation_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('query', 'Query'), ('install_extension', 'Install Extension'), ('lock_scheduled_jobs', 'Lock Scheduled Jobs'), ('unlock_scheduled_jobs', 'Unlock Scheduled Jobs'), ('terminate_sessions', 'Terminate Sessions'), ('block_sessions', 'Block Sessions'), ('unblock_sessions', 'Unblock Sessions')], db_index=True, max_length=32),
        ),
    ]
