# Generated by Django 4.2.25 on 2025-12-07 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_batchoperation_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJobRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_index=True, help_text="Name of the scheduled job (e.g., 'health_check', 'sync_clusters')", max_length=100)),
                ('worker_instance', models.CharField(help_text='Hostname or pod name of the worker that executed the job', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('result_summary', models.TextField(blank=True, help_text='Summary of job execution results')),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback for debugging')),
                ('items_processed', models.IntegerField(default=0, help_text='Number of items processed during execution')),
                ('items_failed', models.IntegerField(default=0, help_text='Number of items that failed during execution')),
            ],
            options={
                'verbose_name': 'Scheduler Job Run',
                'verbose_name_plural': 'Scheduler Job Runs',
                'db_table': 'scheduler_job_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_name', 'started_at'], name='scheduler_j_job_nam_b2da36_idx'), models.Index(fields=['status', 'started_at'], name='scheduler_j_status_058e0b_idx'), models.Index(fields=['worker_instance', 'started_at'], name='scheduler_j_worker__6557a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier of the task execution')),
                ('task_type', models.CharField(db_index=True, help_text="Type of task (e.g., 'odata_query', 'lock_sessions')", max_length=100)),
                ('queue_name', models.CharField(help_text='Name of the queue task was pulled from', max_length=100)),
                ('worker_instance', models.CharField(help_text='Hostname or pod name of the worker that executed the task', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('input_summary', models.JSONField(default=dict, help_text='Summary of input parameters (only key data)')),
                ('result_summary', models.JSONField(default=dict, help_text='Summary of execution results')),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed')),
                ('error_type', models.CharField(blank=True, help_text="Exception class name (e.g., 'TimeoutError', 'ConnectionError')", max_length=255)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('operation', models.ForeignKey(blank=True, help_text='Related batch operation if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='operations.batchoperation')),
            ],
            options={
                'verbose_name': 'Task Execution Log',
                'verbose_name_plural': 'Task Execution Logs',
                'db_table': 'task_execution_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_id'], name='task_execut_task_id_23d47f_idx'), models.Index(fields=['task_type', 'started_at'], name='task_execut_task_ty_ef9eb0_idx'), models.Index(fields=['status', 'started_at'], name='task_execut_status_73b84b_idx'), models.Index(fields=['operation', 'started_at'], name='task_execut_operati_8cbab6_idx'), models.Index(fields=['worker_instance', 'started_at'], name='task_execut_worker__312225_idx')],
            },
        ),
    ]
