# Generated by Django 4.2.25 on 2025-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_rename_celery_task_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batchoperation',
            name='batch_opera_celery__b92516_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_celery__c69876_idx',
        ),
        migrations.AddIndex(
            model_name='batchoperation',
            index=models.Index(fields=['task_id'], name='batch_opera_task_id_a23f41_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='tasks_task_id_869377_idx'),
        ),
    ]
