# Generated by Django 4.2.25 on 2025-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_rename_celery_task_id_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchoperation',
            name='operation_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('query', 'Query'), ('install_extension', 'Install Extension'), ('lock_scheduled_jobs', 'Lock Scheduled Jobs'), ('unlock_scheduled_jobs', 'Unlock Scheduled Jobs'), ('terminate_sessions', 'Terminate Sessions'), ('block_sessions', 'Block Sessions'), ('unblock_sessions', 'Unblock Sessions'), ('sync_cluster', 'Sync Cluster'), ('discover_clusters', 'Discover Clusters')], db_index=True, max_length=32),
        ),
    ]
