# Generated by Codex CLI on 2025-12-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_batchoperation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerjobrun',
            name='job_config',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional job configuration provided by worker',
            ),
        ),
    ]

