# Generated by Django 4.2.25 on 2025-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_schedulerjobrun_job_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20),
        ),
    ]
