# Generated by Django 4.2.25 on 2025-12-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0012_alter_taskexecutionlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Action identifier (e.g. dlq.retry)', max_length=128)),
                ('outcome', models.CharField(choices=[('success', 'success'), ('error', 'error')], db_index=True, max_length=16)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Audit Log',
                'verbose_name_plural': 'Admin Action Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='operations__action_561cf1_idx'), models.Index(fields=['target_type', 'target_id'], name='operations__target__2a776d_idx')],
            },
        ),
    ]
