# Generated by Django 6.0 on 2026-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_batchoperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchoperation',
            name='operation_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('query', 'Query'), ('lock_scheduled_jobs', 'Lock Scheduled Jobs'), ('unlock_scheduled_jobs', 'Unlock Scheduled Jobs'), ('terminate_sessions', 'Terminate Sessions'), ('block_sessions', 'Block Sessions'), ('unblock_sessions', 'Unblock Sessions'), ('sync_cluster', 'Sync Cluster'), ('discover_clusters', 'Discover Clusters'), ('health_check', 'Health Check'), ('ibcmd_backup', 'IBCMD Backup'), ('ibcmd_restore', 'IBCMD Restore'), ('ibcmd_replicate', 'IBCMD Replicate'), ('ibcmd_create', 'IBCMD Create'), ('ibcmd_load_cfg', 'IBCMD Load Config/Extension'), ('ibcmd_extension_update', 'IBCMD Extension Update'), ('designer_cli', 'Designer CLI')], db_index=True, max_length=32),
        ),
    ]
