# Generated by Django 6.0 on 2026-01-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_alter_batchoperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='databases.database'),
        ),
    ]

