# Generated by Django 6.0 on 2026-01-08 12:00

from django.db import migrations


LEGACY_IBCMD_TYPES = (
    "ibcmd_backup",
    "ibcmd_restore",
    "ibcmd_replicate",
    "ibcmd_create",
    "ibcmd_load_cfg",
    "ibcmd_extension_update",
)


def delete_legacy_ibcmd_batch_operations(apps, schema_editor) -> None:
    BatchOperation = apps.get_model("operations", "BatchOperation")
    BatchOperation.objects.filter(operation_type__in=LEGACY_IBCMD_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0021_drivercommandshortcut"),
    ]

    operations = [
        migrations.RunPython(delete_legacy_ibcmd_batch_operations, migrations.RunPython.noop),
    ]

