# Generated by Django 6.0 on 2026-01-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_delete_legacy_ibcmd_batch_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchoperation',
            name='operation_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('query', 'Query'), ('lock_scheduled_jobs', 'Lock Scheduled Jobs'), ('unlock_scheduled_jobs', 'Unlock Scheduled Jobs'), ('terminate_sessions', 'Terminate Sessions'), ('block_sessions', 'Block Sessions'), ('unblock_sessions', 'Unblock Sessions'), ('sync_cluster', 'Sync Cluster'), ('discover_clusters', 'Discover Clusters'), ('health_check', 'Health Check'), ('ibcmd_cli', 'IBCMD CLI (schema-driven)'), ('designer_cli', 'Designer CLI')], db_index=True, max_length=32),
        ),
    ]
