# Generated by Django 6.0 on 2026-01-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0025_drivercommandshortcut_payload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchoperation",
            options={
                "ordering": ["-created_at"],
                "permissions": (
                    ("execute_safe_operation", "Can execute safe operations"),
                    ("execute_dangerous_operation", "Can execute dangerous operations"),
                    ("use_service_ib_auth", "Can use service infobase authentication"),
                    ("use_service_dbms_auth", "Can use service DBMS authentication"),
                    ("cancel_operation", "Can cancel operations"),
                    ("view_operation_logs", "Can view operation logs"),
                    ("manage_driver_catalogs", "Can manage driver catalogs"),
                ),
                "verbose_name": "Batch Operation",
                "verbose_name_plural": "Batch Operations",
            },
        ),
    ]

