# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0026_batchoperation_service_dbms_auth_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamMessageReceipt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stream", models.CharField(max_length=255)),
                ("group", models.CharField(max_length=255)),
                ("message_id", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(blank=True, max_length=128)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("handler", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "stream_message_receipts",
            },
        ),
        migrations.AddConstraint(
            model_name="streammessagereceipt",
            constraint=models.UniqueConstraint(
                fields=("stream", "group", "message_id"),
                name="uq_stream_message_receipt_stream_group_message_id",
            ),
        ),
        migrations.AddIndex(
            model_name="streammessagereceipt",
            index=models.Index(fields=["processed_at"], name="operations_s_processed_7b2eb3_idx"),
        ),
        migrations.AddIndex(
            model_name="streammessagereceipt",
            index=models.Index(fields=["stream", "group"], name="operations_s_stream_g_1a7b57_idx"),
        ),
    ]

