# Generated by Django 6.0 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0027_stream_message_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("publish_failure", "Publish failure"),
                    ("poison_message", "Poison message"),
                ],
                default="publish_failure",
                max_length=32,
            ),
        ),
    ]

