# Generated by Django 6.0 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0028_failed_event_kind"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="failedevent",
            index=models.Index(
                fields=["kind", "status", "created_at"],
                name="operations_f_kind_st_3d5d33_idx",
            ),
        ),
    ]

