# Generated by ChatGPT on 2026-01-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_seed_default_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0030_command_result_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionsPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("database_ids", models.JSONField(default=list)),
                ("preconditions", models.JSONField(default=dict, help_text="database_id -> {hash, at}")),
                ("executor", models.JSONField(default=dict, help_text="Executor config for apply")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extensions_plans", to="tenancy.tenant")),
            ],
            options={
                "db_table": "extensions_plans",
            },
        ),
        migrations.AddIndex(
            model_name="extensionsplan",
            index=models.Index(fields=["tenant", "-created_at"], name="extensions_tenant__c4f6e8_idx"),
        ),
    ]

