# Generated by Django 6.0 on 2026-01-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_extensions_plans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commandresultsnapshot',
            new_name='command_res_tenant__2b6f75_idx',
            old_name='command_res_tenant__40e42e_idx',
        ),
        migrations.RenameIndex(
            model_name='commandresultsnapshot',
            new_name='command_res_tenant__919e15_idx',
            old_name='command_res_tenant__0fc17c_idx',
        ),
        migrations.RenameIndex(
            model_name='extensionsplan',
            new_name='extensions__tenant__17ae2e_idx',
            old_name='extensions_tenant__c4f6e8_idx',
        ),
        migrations.RenameIndex(
            model_name='failedevent',
            new_name='failed_even_kind_f07ccb_idx',
            old_name='operations_f_kind_st_3d5d33_idx',
        ),
        migrations.RenameIndex(
            model_name='streammessagereceipt',
            new_name='stream_mess_process_3fa370_idx',
            old_name='operations_s_processed_7b2eb3_idx',
        ),
        migrations.RenameIndex(
            model_name='streammessagereceipt',
            new_name='stream_mess_stream_1b6c82_idx',
            old_name='operations_s_stream_g_1a7b57_idx',
        ),
    ]
