# Generated by Django 6.0 on 2026-02-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_rename_command_res_tenant__40e42e_idx_command_res_tenant__2b6f75_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchoperation',
            name='template',
        ),
    ]
