# Generated by Django 6.0 on 2026-02-20 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_remove_batchoperation_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEnqueueOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('stream_name', models.CharField(default='commands:worker:workflows', max_length=128)),
                ('message_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched')], db_index=True, default='pending', max_length=16)),
                ('dispatch_attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('stream_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_enqueue_outbox',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='workflow_en_status_33c76a_idx'), models.Index(fields=['operation_id', 'status'], name='workflow_en_operati_e1f2a7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stream_name', ''), _negated=True), name='chk_workflow_enqueue_outbox_stream_name_nonempty')],
            },
        ),
    ]
