# Generated by Django 6.0 on 2026-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_workflowenqueueoutbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowenqueueoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
