# Generated by Django 6.0 on 2026-04-10 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0036_batchoperation_manage_runtime_controls_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeActionRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(db_index=True, default="local_scripts", max_length=64)),
                ("runtime_id", models.CharField(db_index=True, max_length=128)),
                ("runtime_name", models.CharField(db_index=True, max_length=64)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("probe", "Probe"),
                            ("restart", "Restart"),
                            ("tail_logs", "Tail Logs"),
                            ("trigger_now", "Trigger Now"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_job_name", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="accepted",
                        max_length=16,
                    ),
                ),
                ("requested_by_username", models.CharField(blank=True, default="", max_length=150)),
                ("reason", models.TextField(blank=True, default="")),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("result_excerpt", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_action_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduler_job_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_action_runs",
                        to="operations.schedulerjobrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Runtime Action Run",
                "verbose_name_plural": "Runtime Action Runs",
                "db_table": "runtime_action_runs",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="runtimeactionrun",
            index=models.Index(fields=["runtime_id", "requested_at"], name="runtime_act_runtime_d83b84_idx"),
        ),
        migrations.AddIndex(
            model_name="runtimeactionrun",
            index=models.Index(fields=["action_type", "requested_at"], name="runtime_act_action__60c945_idx"),
        ),
        migrations.AddIndex(
            model_name="runtimeactionrun",
            index=models.Index(fields=["status", "requested_at"], name="runtime_act_status_c183d1_idx"),
        ),
        migrations.AddIndex(
            model_name="runtimeactionrun",
            index=models.Index(fields=["target_job_name", "requested_at"], name="runtime_act_target__b6216f_idx"),
        ),
    ]
