# Generated by Django 6.0 on 2026-04-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_runtimeactionrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runtimeactionrun',
            new_name='runtime_act_runtime_667e36_idx',
            old_name='runtime_act_runtime_d83b84_idx',
        ),
        migrations.RenameIndex(
            model_name='runtimeactionrun',
            new_name='runtime_act_action__349030_idx',
            old_name='runtime_act_action__60c945_idx',
        ),
        migrations.RenameIndex(
            model_name='runtimeactionrun',
            new_name='runtime_act_status_7ff353_idx',
            old_name='runtime_act_status_c183d1_idx',
        ),
        migrations.RenameIndex(
            model_name='runtimeactionrun',
            new_name='runtime_act_target__6c95bb_idx',
            old_name='runtime_act_target__b6216f_idx',
        ),
    ]
