# Generated by Django 4.2.7 on 2025-10-20 17:48

from django.db import migrations, models
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=80)),
                ("base_name", models.CharField(max_length=255)),
                ("odata_url", models.URLField(max_length=512)),
                ("username", models.CharField(max_length=255)),
                ("password", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "max_connections",
                    models.IntegerField(
                        default=10, help_text="Maximum concurrent connections"
                    ),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(
                        default=30, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                (
                    "last_check_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("health_check_enabled", models.BooleanField(default=True)),
                (
                    "avg_response_time",
                    models.FloatField(
                        blank=True,
                        help_text="Average response time in milliseconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "1C Database",
                "verbose_name_plural": "1C Databases",
                "db_table": "databases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseGroup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "databases",
                    models.ManyToManyField(
                        related_name="groups", to="databases.database"
                    ),
                ),
            ],
            options={
                "verbose_name": "Database Group",
                "verbose_name_plural": "Database Groups",
                "db_table": "database_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="database",
            index=models.Index(
                fields=["status", "last_check_status"],
                name="databases_status_f7d779_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="database",
            index=models.Index(
                fields=["last_check"], name="databases_last_ch_62439e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="database",
            index=models.Index(
                fields=["consecutive_failures"], name="databases_consecu_e29978_idx"
            ),
        ),
    ]
