# Generated by Django 5.2.7 on 2025-10-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension_name",
                    models.CharField(default="ODataAutoConfig", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_installations",
                        to="databases.database",
                    ),
                ),
            ],
            options={
                "db_table": "databases_extension_installation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="databases_e_status_e9e15e_idx"
                    ),
                    models.Index(
                        fields=["database", "extension_name"],
                        name="databases_e_databas_599217_idx",
                    ),
                ],
            },
        ),
    ]
