# Generated by Django 4.2.9 on 2025-10-28 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0003_add_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Cluster UUID from 1C",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Cluster name from 1C", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "ras_server",
                    models.CharField(
                        default="localhost:1545",
                        help_text="RAS server address (host:port)",
                        max_length=255,
                    ),
                ),
                (
                    "installation_service_url",
                    models.URLField(
                        help_text="URL of installation-service managing this cluster",
                        max_length=512,
                    ),
                ),
                (
                    "cluster_user",
                    models.CharField(
                        blank=True,
                        help_text="Cluster admin username (if required)",
                        max_length=255,
                    ),
                ),
                (
                    "cluster_pwd",
                    models.CharField(
                        blank=True, help_text="Cluster admin password", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, help_text="Last sync timestamp", null=True
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "last_sync_error",
                    models.TextField(
                        blank=True, help_text="Error message from last sync"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional cluster metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "1C Cluster",
                "verbose_name_plural": "1C Clusters",
                "db_table": "clusters",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="database",
            name="databases_status_f7d779_idx",
        ),
        migrations.AlterField(
            model_name="database",
            name="base_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Infobase name from 1C cluster",
                max_length=255,
            ),
        ),
        # ADD FIELD FIRST, BEFORE CREATING INDEXES
        migrations.AddField(
            model_name="database",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="1C Cluster this infobase belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="databases",
                to="databases.cluster",
            ),
        ),
        # NOW CREATE INDEXES (AFTER FIELD EXISTS)
        migrations.AddIndex(
            model_name="database",
            index=models.Index(
                fields=["cluster", "status"], name="databases_cluster_dbef30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="database",
            index=models.Index(fields=["status"], name="databases_status_db779d_idx"),
        ),
        migrations.AddIndex(
            model_name="database",
            index=models.Index(
                fields=["base_name"], name="databases_base_na_3c70f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["status", "last_sync_status"], name="clusters_status_b64016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["last_sync"], name="clusters_last_sy_8d97fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["ras_server"], name="clusters_ras_ser_50ea83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cluster",
            constraint=models.UniqueConstraint(
                fields=("ras_server", "name"), name="unique_cluster_per_ras_server"
            ),
        ),
    ]
