# Generated by Django 5.2.7 on 2025-10-28 16:16

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "databases",
            "0004_cluster_remove_database_databases_status_f7d779_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="cluster_pwd",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Cluster admin password (encrypted)"
            ),
        ),
    ]
