# Generated by Django 4.2.9 on 2025-10-28 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0005_encrypt_cluster_pwd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Cluster UUID (auto-generated or from 1C)",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
