# Generated by Django 5.2.7 on 2025-10-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0006_change_cluster_id_to_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='installation_service_url',
            new_name='cluster_service_url',
        ),
    ]
