# Generated by Django 5.2.7 on 2025-10-31 15:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0007_rename_installation_service_to_cluster_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Batch Service UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Batch Service instance name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Batch Service endpoint URL (e.g., http://localhost:8087)",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this service is active and available for use",
                    ),
                ),
                (
                    "last_health_check",
                    models.DateTimeField(
                        blank=True, help_text="Last health check timestamp", null=True
                    ),
                ),
                (
                    "last_health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        help_text="Result of last health check",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., last_error, performance stats)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Service",
                "verbose_name_plural": "Batch Services",
                "db_table": "batch_services",
                "ordering": ["-is_active", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "last_health_status"],
                        name="batch_servi_is_acti_1e4c19_idx",
                    ),
                    models.Index(
                        fields=["last_health_check"],
                        name="batch_servi_last_he_5bfcc3_idx",
                    ),
                ],
            },
        ),
    ]
