# Generated by Django 5.2.7 on 2025-11-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("databases", "0008_add_batch_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchservice",
            name="consecutive_failures",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive health check failures"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="consecutive_failures",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive health check failures"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="last_health_check",
            field=models.DateTimeField(
                blank=True, help_text="Last health check timestamp", null=True
            ),
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("old_status", models.CharField(max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "db_table": "status_history",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-changed_at"],
                        name="status_hist_content_ea404c_idx",
                    ),
                    models.Index(
                        fields=["new_status", "-changed_at"],
                        name="status_hist_new_sta_7cf840_idx",
                    ),
                ],
            },
        ),
    ]
