# Generated by Django 4.2.25 on 2025-11-01 15:24

from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    """
    Convert is_active (bool) to status (CharField).

    Mapping:
    - is_active=True → status='active'
    - is_active=False → status='inactive'
    - is_active=None → status='inactive' (fallback)
    """
    BatchService = apps.get_model('databases', 'BatchService')

    for service in BatchService.objects.all():
        # Explicit check for None to avoid unexpected behavior
        if service.is_active is True:
            service.status = 'active'
        elif service.is_active is False:
            service.status = 'inactive'
        else:
            # Fallback for NULL values (should not happen, but be safe)
            service.status = 'inactive'
        service.save(update_fields=['status'])


def reverse_migrate_status_to_is_active(apps, schema_editor):
    """
    Reverse migration: status → is_active.

    Mapping:
    - status='active' → is_active=True
    - status in ('inactive', 'error', 'maintenance') → is_active=False
    """
    BatchService = apps.get_model('databases', 'BatchService')

    for service in BatchService.objects.all():
        if service.status == 'active':
            service.is_active = True
        else:
            service.is_active = False
        service.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0009_add_health_check_fields"),
    ]

    operations = [
        # 1. Add status field (with default='active')
        migrations.AddField(
            model_name="batchservice",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                    ("maintenance", "Maintenance"),
                ],
                db_index=True,
                default="active",
                help_text="Service status (unified with Cluster/Database)",
                max_length=20,
            ),
        ),

        # 2. Migrate data: is_active → status
        migrations.RunPython(
            migrate_is_active_to_status,
            reverse_migrate_status_to_is_active
        ),

        # 3. Remove old index
        migrations.RemoveIndex(
            model_name="batchservice",
            name="batch_servi_is_acti_1e4c19_idx",
        ),

        # 4. Add new index
        migrations.AddIndex(
            model_name="batchservice",
            index=models.Index(
                fields=["status", "last_health_status"],
                name="batch_servi_status_71c34a_idx",
            ),
        ),

        # 5. Update ordering (Meta)
        migrations.AlterModelOptions(
            name="batchservice",
            options={
                "ordering": ["name"],
                "verbose_name": "Batch Service",
                "verbose_name_plural": "Batch Services",
            },
        ),

        # 6. Remove is_active field
        migrations.RemoveField(
            model_name="batchservice",
            name="is_active",
        ),
    ]
