# Generated by Django 4.2.9 on 2025-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0010_migrate_batch_service_to_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="infobase_name",
            field=models.CharField(
                blank=True,
                help_text="Имя информационной базы на сервере 1С (если отличается от name)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="server_address",
            field=models.CharField(
                default="localhost",
                help_text="Адрес сервера 1С (например: localhost, srv1c, 192.168.1.100)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="server_port",
            field=models.IntegerField(
                default=1540, help_text="Порт сервера 1С (обычно 1540 или 1541)"
            ),
        ),
    ]
