# Generated by Django 4.2.9 on 2025-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0011_add_server_connection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="ras_cluster_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID кластера 1С в RAS (для блокировки регламентных заданий)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="ras_infobase_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID информационной базы в RAS (может отличаться от primary key)",
                null=True,
            ),
        ),
    ]
