# Generated by Django 4.2.25 on 2025-12-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0012_add_cluster_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='ras_cluster_uuid',
            field=models.UUIDField(blank=True, help_text='UUID кластера в RAS (заполняется при первой успешной синхронизации)', null=True),
        ),
    ]
