# Generated by Django 4.2.25 on 2025-12-09 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def grant_staff_cluster_access(apps, schema_editor):
    """Grant ADMIN access to all staff users on all clusters."""
    User = apps.get_model('auth', 'User')
    Cluster = apps.get_model('databases', 'Cluster')
    ClusterPermission = apps.get_model('databases', 'ClusterPermission')

    staff_users = User.objects.filter(is_staff=True)
    clusters = Cluster.objects.all()

    for user in staff_users:
        for cluster in clusters:
            ClusterPermission.objects.get_or_create(
                user=user,
                cluster=cluster,
                defaults={
                    'level': 40,  # ADMIN
                    'notes': 'Auto-granted during RBAC migration'
                }
            )


def reverse_grant(apps, schema_editor):
    """Remove auto-granted permissions on rollback."""
    ClusterPermission = apps.get_model('databases', 'ClusterPermission')
    ClusterPermission.objects.filter(notes='Auto-granted during RBAC migration').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databases', '0013_add_ras_cluster_uuid_to_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='databases.database')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'databases_database_permissions',
                'indexes': [models.Index(fields=['user', 'database'], name='dp_user_db_idx'), models.Index(fields=['database', 'level'], name='dp_db_level_idx')],
                'unique_together': {('user', 'database')},
            },
        ),
        migrations.CreateModel(
            name='ClusterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='databases.cluster')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'databases_cluster_permissions',
                'indexes': [models.Index(fields=['user', 'cluster'], name='cp_user_cluster_idx'), models.Index(fields=['cluster', 'level'], name='cp_cluster_level_idx')],
                'unique_together': {('user', 'cluster')},
            },
        ),
        # Data migration: grant ADMIN to all staff users on all clusters
        migrations.RunPython(grant_staff_cluster_access, reverse_grant),
    ]
