# Generated by Django 4.2.25 on 2025-12-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0015_remove_batch_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_service_url',
            field=models.URLField(help_text='Legacy URL for cluster integrations (currently unused)', max_length=512),
        ),
    ]
