# Generated by Django 6.0 on 2026-01-07 11:52

import apps.databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0020_add_cluster_connection_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['name'], 'permissions': (('operate_cluster', 'Can operate cluster'), ('manage_cluster', 'Can manage cluster'), ('admin_cluster', 'Can administer cluster')), 'verbose_name': '1C Cluster', 'verbose_name_plural': '1C Clusters'},
        ),
        migrations.AlterModelOptions(
            name='clusterpermission',
            options={'permissions': (('manage_rbac', 'Can manage RBAC'),)},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['name'], 'permissions': (('operate_database', 'Can operate database'), ('manage_database', 'Can manage database'), ('admin_database', 'Can administer database')), 'verbose_name': '1C Database', 'verbose_name_plural': '1C Databases'},
        ),
        migrations.AlterField(
            model_name='database',
            name='id',
            field=models.CharField(default=apps.databases.models.generate_database_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
