# Generated by Django 6.0 on 2026-01-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('databases', '0021_alter_cluster_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='databases.cluster')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_permissions', to='auth.group')),
            ],
            options={
                'db_table': 'databases_cluster_group_permissions',
                'indexes': [models.Index(fields=['group', 'cluster'], name='cgp_group_cluster_idx'), models.Index(fields=['cluster', 'level'], name='cgp_cluster_level_idx')],
                'unique_together': {('group', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'View'), (20, 'Operate'), (30, 'Manage'), (40, 'Admin')], default=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='databases.database')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_permissions', to='auth.group')),
            ],
            options={
                'db_table': 'databases_database_group_permissions',
                'indexes': [models.Index(fields=['group', 'database'], name='dgp_group_db_idx'), models.Index(fields=['database', 'level'], name='dgp_db_level_idx')],
                'unique_together': {('group', 'database')},
            },
        ),
    ]
