# Generated by Django 6.0 on 2026-01-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0022_clustergrouppermission_databasegrouppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseExtensionsSnapshot',
            fields=[
                ('database', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extensions_snapshot', serialize=False, to='databases.database')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('source_operation_id', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'databases_extensions_snapshot',
            },
        ),
        migrations.AddIndex(
            model_name='databaseextensionssnapshot',
            index=models.Index(fields=['-updated_at'], name='databases_ex_updated_95f8f9_idx'),
        ),
    ]
