# Generated by Django 6.0 on 2026-01-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0023_databaseextensionssnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='databaseextensionssnapshot',
            new_name='databases_e_updated_d4ad20_idx',
            old_name='databases_ex_updated_95f8f9_idx',
        ),
    ]
