# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models
import django.db.models.deletion


def _assign_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    Cluster = apps.get_model("databases", "Cluster")
    Database = apps.get_model("databases", "Database")

    default_tenant, _ = Tenant.objects.get_or_create(slug="default", defaults={"name": "Default"})

    Cluster.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Database.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_seed_default_tenant"),
        ("databases", "0025_add_dbms_user_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clusters",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="databases",
                to="tenancy.tenant",
            ),
        ),
        migrations.RunPython(_assign_default_tenant, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cluster",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clusters",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="database",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="databases",
                to="tenancy.tenant",
            ),
        ),
    ]

