# Generated by Django 6.0 on 2026-01-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0026_tenancy_fk'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this cluster', on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='database',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this database', on_delete=django.db.models.deletion.PROTECT, related_name='databases', to='tenancy.tenant'),
        ),
    ]
