/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Class-aware request budgets для authenticated `/api/v2` traffic
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */
import type { ClusterStatus } from "./clusterStatus";

export interface Cluster {
  id?: string;
  name?: string;
  ras_host?: string;
  ras_port?: number;
  readonly ras_server?: string;
  rmngr_host?: string;
  rmngr_port?: number;
  ragent_host?: string;
  ragent_port?: number;
  rphost_port_from?: number;
  rphost_port_to?: number;
  cluster_service_url?: string;
  status?: ClusterStatus;
  /** @nullable */
  last_sync?: string | null;
}
