/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Rate limiting (100 req/min per user)
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */

export interface ClusterCreate {
  name: string;
  ras_host: string;
  ras_port: number;
  rmngr_host: string;
  rmngr_port: number;
  ragent_host?: string;
  ragent_port?: number;
  rphost_port_from?: number;
  rphost_port_to?: number;
  cluster_service_url: string;
  cluster_user?: string;
  cluster_pwd?: string;
}
