/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Class-aware request budgets для authenticated `/api/v2` traffic
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */

/**
 * Gateway request-budget class that produced the `429`.
 */
export type GatewayRateLimitClass =
  (typeof GatewayRateLimitClass)[keyof typeof GatewayRateLimitClass];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GatewayRateLimitClass = {
  shell_critical: "shell_critical",
  interactive: "interactive",
  background_heavy: "background_heavy",
  telemetry: "telemetry",
} as const;
