/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Class-aware request budgets для authenticated `/api/v2` traffic
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */
import type { GatewayRateLimitExceededResponseDetails } from "./gatewayRateLimitExceededResponseDetails";
import type { GatewayRateLimitClass } from "./gatewayRateLimitClass";

export interface GatewayRateLimitExceededResponse {
  error: string;
  code: string;
  details?: GatewayRateLimitExceededResponseDetails;
  /** Stable gateway correlation identifier for the rejected request. */
  request_id: string;
  /** Optional frontend action correlation identifier echoed by the gateway. */
  ui_action_id?: string;
  rate_limit_class: GatewayRateLimitClass;
  /**
   * Recommended backoff window for the exhausted budget class.
   * @minimum 1
   */
  retry_after_seconds: number;
  /** Human-readable budget key emitted by the gateway for diagnostics. */
  budget_scope: string;
}
