/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Rate limiting (100 req/min per user)
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */

export type GetTracingGetTracesParams = {
  /**
   * Service name (required by Jaeger)
   */
  service: string;
  /**
   * Operation name (optional)
   */
  operation?: string;
  /**
   * Maximum number of traces
   */
  limit?: number;
  /**
   * Lookback window (e.g., 1h, 30m)
   */
  lookback?: string;
  /**
   * Start time in microseconds since epoch (Jaeger)
   */
  start?: string;
  /**
   * End time in microseconds since epoch (Jaeger)
   */
  end?: string;
};
