/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Rate limiting (100 req/min per user)
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */
import type { HealthStatusStatus } from "./healthStatusStatus";

export interface HealthStatus {
  status?: HealthStatusStatus;
  last_check?: string;
  response_time_ms?: number;
}
