/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CommandCenter1C API Gateway
 * Единая точка входа для Frontend приложения CommandCenter1C.

API Gateway выполняет функции:
- JWT аутентификация
- Rate limiting (100 req/min per user)
- Проксирование запросов к Orchestrator
- CORS handling

**Архитектура:**
```
Frontend → API Gateway (8080) → Orchestrator (8000) → Микросервисы
```

**Важно:** Большинство endpoints проксируются в Django Orchestrator.
Schemas описывают итоговые response от всей системы.

 * OpenAPI spec version: 1.0.0
 */
import type { OperationOperationType } from "./operationOperationType";
import type { OperationStatus } from "./operationStatus";

export interface Operation {
  id?: string;
  operation_type?: OperationOperationType;
  status?: OperationStatus;
  /**
   * @minimum 0
   * @maximum 100
   */
  progress?: number;
  created_at?: string;
  updated_at?: string;
  /** @nullable */
  completed_at?: string | null;
}
