#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGETS_DIR="$PROJECT_ROOT/infrastructure/monitoring/prometheus/targets"
TARGET_FILE="$TARGETS_DIR/blackbox_tcp.yml"

# Load env (prefer already exported vars from caller, fallback to .env.local)
if [[ -z "${RAS_SERVER_ADDR:-}" ]] && [[ -f "$PROJECT_ROOT/.env.local" ]]; then
  # shellcheck disable=SC1091
  set -a
  source "$PROJECT_ROOT/.env.local"
  set +a
fi

RAS_TARGET="${RAS_SERVER_ADDR:-${RAS_SERVER:-}}"

if [[ -z "${RAS_TARGET:-}" ]]; then
  echo "ERROR: RAS_SERVER_ADDR (or RAS_SERVER) is not set; cannot generate blackbox targets." >&2
  exit 1
fi

mkdir -p "$TARGETS_DIR"

cat > "$TARGET_FILE" <<EOF
# Generated by scripts/dev/generate-blackbox-targets.sh
# Source of truth: .env.local (RAS_SERVER_ADDR)
- targets:
  - "${RAS_TARGET}"
  labels:
    cc1c_service: "ras-server"
    ras_target: "${RAS_TARGET}"
EOF

echo "OK: wrote ${TARGET_FILE} (target=${RAS_TARGET})"

