#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGETS_DIR="$PROJECT_ROOT/infrastructure/monitoring/prometheus/targets"
TCP_TARGET_FILE="$TARGETS_DIR/blackbox_tcp.yml"
HTTP_TARGET_FILE="$TARGETS_DIR/blackbox_http.yml"

# Load env (prefer already exported vars from caller, fallback to .env.local)
if [[ -z "${RAS_SERVER_ADDR:-}" ]] && [[ -f "$PROJECT_ROOT/.env.local" ]]; then
  # shellcheck disable=SC1091
  set -a
  source "$PROJECT_ROOT/.env.local"
  set +a
fi

RAS_TARGET="${RAS_SERVER_ADDR:-${RAS_SERVER:-}}"

if [[ -z "${RAS_TARGET:-}" ]]; then
  echo "ERROR: RAS_SERVER_ADDR (or RAS_SERVER) is not set; cannot generate blackbox targets." >&2
  exit 1
fi

FRONTEND_TARGET=""
if [[ -n "${FRONTEND_URL:-}" ]]; then
  FRONTEND_TARGET="${FRONTEND_URL%/}/"
else
  BASE_HOST="${CC1C_BASE_HOST:-localhost}"
  if [[ "${USE_DOCKER:-false}" == "true" ]]; then
    BASE_HOST="host.docker.internal"
  fi
  FRONTEND_PORT="${FRONTEND_PORT:-5173}"
  FRONTEND_TARGET="http://${BASE_HOST}:${FRONTEND_PORT}/"
fi

mkdir -p "$TARGETS_DIR"

cat > "$TCP_TARGET_FILE" <<EOF
# Generated by scripts/dev/generate-blackbox-targets.sh
# Source of truth: .env.local (RAS_SERVER_ADDR)
- targets:
  - "${RAS_TARGET}"
  labels:
    cc1c_service: "ras-server"
    ras_target: "${RAS_TARGET}"
EOF

cat > "$HTTP_TARGET_FILE" <<EOF
# Generated by scripts/dev/generate-blackbox-targets.sh
# Source of truth: .env.local (CC1C_BASE_HOST / FRONTEND_URL)
- targets:
  - "${FRONTEND_TARGET}"
  labels:
    cc1c_service: "frontend"
    frontend_target: "${FRONTEND_TARGET}"
EOF

echo "OK: wrote ${TCP_TARGET_FILE} (target=${RAS_TARGET})"
echo "OK: wrote ${HTTP_TARGET_FILE} (target=${FRONTEND_TARGET})"
