# Generated by Django 6.0 on 2026-02-12 17:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=512)),
                ('inn', models.CharField(help_text='Taxpayer identification number', max_length=12)),
                ('kpp', models.CharField(blank=True, help_text='Reason code for registration', max_length=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('external_ref', models.CharField(blank=True, help_text='External system reference', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_pools', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'organization_pools',
            },
        ),
        migrations.CreateModel(
            name='PoolNodeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_root', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_node_versions', to='intercompany_pools.organization')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_versions', to='intercompany_pools.organizationpool')),
            ],
            options={
                'db_table': 'pool_node_versions',
            },
        ),
        migrations.CreateModel(
            name='PoolEdgeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_versions', to='intercompany_pools.organizationpool')),
                ('child_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='intercompany_pools.poolnodeversion')),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='intercompany_pools.poolnodeversion')),
            ],
            options={
                'db_table': 'pool_edge_versions',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'inn'], name='pool_organi_tenant__47fac1_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'status'], name='pool_organi_tenant__b85a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', '-updated_at'], name='pool_organi_tenant__b35d5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'inn'), name='uniq_pool_org_tenant_inn'),
        ),
        migrations.AddIndex(
            model_name='organizationpool',
            index=models.Index(fields=['tenant', 'is_active'], name='organizatio_tenant__9ce953_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpool',
            index=models.Index(fields=['tenant', '-updated_at'], name='organizatio_tenant__9827fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationpool',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_pool_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='poolnodeversion',
            index=models.Index(fields=['pool', 'effective_from'], name='pool_node_v_pool_id_f58868_idx'),
        ),
        migrations.AddIndex(
            model_name='poolnodeversion',
            index=models.Index(fields=['pool', 'effective_to'], name='pool_node_v_pool_id_e5ddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='poolnodeversion',
            index=models.Index(fields=['organization', 'effective_from'], name='pool_node_v_organiz_f76b35_idx'),
        ),
        migrations.AddIndex(
            model_name='poolnodeversion',
            index=models.Index(fields=['pool', 'is_root'], name='pool_node_v_pool_id_7649a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolnodeversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_pool_node_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='poolnodeversion',
            constraint=models.UniqueConstraint(fields=('pool', 'organization', 'effective_from'), name='uniq_pool_node_version_start'),
        ),
        migrations.AddIndex(
            model_name='pooledgeversion',
            index=models.Index(fields=['pool', 'effective_from'], name='pool_edge_v_pool_id_c94f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='pooledgeversion',
            index=models.Index(fields=['pool', 'effective_to'], name='pool_edge_v_pool_id_3b530d_idx'),
        ),
        migrations.AddIndex(
            model_name='pooledgeversion',
            index=models.Index(fields=['parent_node', 'effective_from'], name='pool_edge_v_parent__d925e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pooledgeversion',
            index=models.Index(fields=['child_node', 'effective_from'], name='pool_edge_v_child_n_41f8b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooledgeversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_pool_edge_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='pooledgeversion',
            constraint=models.CheckConstraint(condition=models.Q(('parent_node', models.F('child_node')), _negated=True), name='chk_pool_edge_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='pooledgeversion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='chk_pool_edge_positive_weight'),
        ),
        migrations.AddConstraint(
            model_name='pooledgeversion',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__isnull', True), ('max_amount__isnull', True), ('max_amount__gte', models.F('min_amount')), _connector='OR'), name='chk_pool_edge_amount_bounds'),
        ),
        migrations.AddConstraint(
            model_name='pooledgeversion',
            constraint=models.UniqueConstraint(fields=('pool', 'parent_node', 'child_node', 'effective_from'), name='uniq_pool_edge_version_start'),
        ),
    ]
