# Generated by Django 6.0 on 2026-02-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='database',
            field=models.OneToOneField(blank=True, help_text='Linked infobase (1:1 mapping).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='databases.database'),
        ),
    ]
