# Generated by Django 6.0 on 2026-02-12 17:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0002_organization_database'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSchemaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('xlsx', 'XLSX'), ('json', 'JSON')], db_index=True, default='xlsx', max_length=16)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('schema', models.JSONField(blank=True, default=dict, help_text='Field mapping and parse settings.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_schema_templates', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_schema_templates',
                'indexes': [models.Index(fields=['tenant', 'is_public', 'is_active'], name='pool_schema_tenant__74d587_idx'), models.Index(fields=['tenant', 'format'], name='pool_schema_tenant__67d303_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_pool_template_tenant_code')],
            },
        ),
    ]
