# Generated by Django 6.0 on 2026-02-12 17:24

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0003_poolschematemplate'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('top_down', 'Top Down'), ('bottom_up', 'Bottom Up')], db_index=True, default='top_down', max_length=16)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('publishing', 'Publishing'), ('partial_success', 'Partial Success'), ('published', 'Published'), ('failed', 'Failed')], default='draft', help_text='Run lifecycle state (FSM-protected).', max_length=50, protected=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('publication_summary', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('publishing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='intercompany_pools.organizationpool')),
                ('schema_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='intercompany_pools.poolschematemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_runs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_runs',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='pool_runs_tenant__be6ee1_idx'), models.Index(fields=['pool', 'period_start'], name='pool_runs_pool_id_61d622_idx'), models.Index(fields=['direction', 'status'], name='pool_runs_directi_03ecc5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='chk_pool_run_period_range')],
            },
        ),
    ]
