# Generated by Django 6.0 on 2026-02-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0004_poolrun'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poolrun',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='poolrun',
            name='mode',
            field=models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], db_index=True, default='safe', max_length=16),
        ),
        migrations.AddField(
            model_name='poolrun',
            name='publication_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poolrun',
            name='publication_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pool_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poolrun',
            name='source_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='poolrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_pool_run_tenant_idempotency_key'),
        ),
    ]
