# Generated by Django 6.0 on 2026-02-12 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0005_poolrun_idempotency_key_poolrun_mode_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRunAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('status_before', models.CharField(blank=True, default='', max_length=32)),
                ('status_after', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='intercompany_pools.poolrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_run_audit_events', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_run_audit_events',
                'indexes': [models.Index(fields=['run', '-created_at'], name='pool_run_au_run_id_d035c8_idx'), models.Index(fields=['tenant', 'event_type', '-created_at'], name='pool_run_au_tenant__6fdcc9_idx')],
            },
        ),
    ]
