# Generated by Django 6.0 on 2026-02-12 17:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0006_poolrunauditevent'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolPublicationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('entity_name', models.CharField(max_length=255)),
                ('documents_count', models.PositiveIntegerField(default=1)),
                ('external_document_identity', models.CharField(blank=True, default='', max_length=128)),
                ('identity_strategy', models.CharField(blank=True, default='', max_length=64)),
                ('posted', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('request_summary', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_attempts', to='intercompany_pools.poolrun')),
                ('target_database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_publication_attempts', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_publication_attempts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_publication_attempts',
                'indexes': [models.Index(fields=['run', 'status', '-created_at'], name='pool_public_run_id_7ae22e_idx'), models.Index(fields=['target_database', 'status', '-created_at'], name='pool_public_target__220b50_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'target_database', 'attempt_number'), name='uniq_pool_publication_attempt_per_target')],
            },
        ),
    ]
