# Generated by Django 6.0 on 2026-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intercompany_pools", "0007_poolpublicationattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolrun",
            name="execution_backend",
            field=models.CharField(blank=True, db_index=True, default="legacy_pool_runtime", max_length=32),
        ),
        migrations.AddField(
            model_name="poolrun",
            name="workflow_execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="poolrun",
            name="workflow_status",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="poolrun",
            name="workflow_template_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
