# Generated by Django 6.0 on 2026-02-13 12:17

import apps.intercompany_pools.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0008_poolrun_workflow_runtime_link'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRunCommandLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('confirm_publication', 'Confirm Publication'), ('abort_publication', 'Abort Publication')], db_index=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('command_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('result_class', models.CharField(choices=[('accepted', 'Accepted'), ('noop', 'No-op'), ('conflict', 'Conflict'), ('bad_request', 'Bad Request'), ('error', 'Error')], max_length=32)),
                ('cas_outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=32)),
                ('response_status_code', models.PositiveSmallIntegerField(default=200)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('last_replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.intercompany_pools.models.get_pool_run_command_log_expires_at)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pool_run_command_logs', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='intercompany_pools.poolrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_run_command_logs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_run_command_log',
                'indexes': [models.Index(fields=['run', 'command_type', '-created_at'], name='pool_run_co_run_id_a4fc92_idx'), models.Index(fields=['tenant', 'command_type', '-created_at'], name='pool_run_co_tenant__045264_idx'), models.Index(fields=['run', 'idempotency_key'], name='pool_run_co_run_id_476416_idx'), models.Index(fields=['expires_at'], name='pool_run_co_expires_ad189a_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'command_type', 'idempotency_key'), name='uniq_pool_run_command_log_scope'), models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='chk_pool_run_command_log_nonempty_key')],
            },
        ),
    ]
