# Generated by Django 6.0 on 2026-02-13 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0009_poolruncommandlog'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRunCommandOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intent_type', models.CharField(choices=[('enqueue_workflow_execution', 'Enqueue Workflow Execution'), ('cancel_workflow_execution', 'Cancel Workflow Execution')], db_index=True, max_length=48)),
                ('stream_name', models.CharField(default='commands:worker:workflows', max_length=128)),
                ('message_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched')], db_index=True, default='pending', max_length=16)),
                ('dispatch_attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('stream_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='intercompany_pools.poolruncommandlog')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_outbox_entries', to='intercompany_pools.poolrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_run_command_outbox', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_run_command_outbox',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='pool_run_co_status_ea52b0_idx'), models.Index(fields=['run', 'status', '-created_at'], name='pool_run_co_run_id_4c68fb_idx'), models.Index(fields=['tenant', 'status', '-created_at'], name='pool_run_co_tenant__204d0a_idx'), models.Index(fields=['command_log', 'intent_type'], name='pool_run_co_command_0fbd31_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stream_name', ''), _negated=True), name='chk_pool_run_command_outbox_stream_name_nonempty'), models.UniqueConstraint(condition=models.Q(('command_log__isnull', False)), fields=('command_log', 'intent_type'), name='uniq_pool_run_command_outbox_command_intent')],
            },
        ),
    ]
