# Generated by Django 6.0 on 2026-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0011_poolrun_workflow_link_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolruncommandlog',
            name='command_type',
            field=models.CharField(choices=[('confirm_publication', 'Confirm Publication'), ('abort_publication', 'Abort Publication'), ('retry_publication', 'Retry Publication')], db_index=True, max_length=32),
        ),
    ]
