# Generated by Django 6.0 on 2026-02-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0012_alter_poolruncommandlog_command_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolrun',
            name='run_input',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
