# Generated by Django 6.0 on 2026-02-18 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0013_poolrun_run_input'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRuntimeStepIdempotencyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workflow_execution_id', models.UUIDField(db_index=True)),
                ('node_id', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('last_replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_step_idempotency_logs', to='intercompany_pools.poolrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_runtime_step_idempotency_logs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_runtime_step_idempotency_log',
                'indexes': [models.Index(fields=['run', 'node_id', '-created_at'], name='pool_runtim_run_id_050bcd_idx'), models.Index(fields=['tenant', 'workflow_execution_id'], name='pool_runtim_tenant__f3d4da_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_pool_runtime_step_idem_tenant_key'), models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='chk_pool_runtime_step_idem_nonempty_key')],
            },
        ),
    ]
