# Generated by Django 6.0 on 2026-02-25 15:40

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0029_extensionflagspolicy"),
        ("intercompany_pools", "0014_poolruntimestepidempotencylog"),
        ("tenancy", "0003_alter_tenant_options_alter_tenantmember_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoolODataMetadataCatalogSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("config_version", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("extensions_fingerprint", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("metadata_hash", models.CharField(max_length=64)),
                ("catalog_version", models.CharField(db_index=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[("live_refresh", "Live Refresh"), ("cold_bootstrap", "Cold Bootstrap")],
                        db_index=True,
                        default="live_refresh",
                        max_length=32,
                    ),
                ),
                ("fetched_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_odata_metadata_catalog_snapshots",
                        to="databases.database",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_odata_metadata_catalog_snapshots",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pool_odata_metadata_catalog_snapshots",
                "indexes": [
                    models.Index(
                        fields=["tenant", "database", "is_current"],
                        name="pool_odata__tenant__a19468_idx",
                    ),
                    models.Index(
                        fields=[
                            "tenant",
                            "database",
                            "config_name",
                            "config_version",
                            "extensions_fingerprint",
                            "is_current",
                        ],
                        name="pool_odata__tenant__ce5220_idx",
                    ),
                    models.Index(fields=["database", "-fetched_at"], name="pool_odata__databas_2628cd_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("metadata_hash", ""), _negated=True),
                        name="chk_pool_meta_catalog_snapshot_metadata_hash_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("catalog_version", ""), _negated=True),
                        name="chk_pool_meta_catalog_snapshot_catalog_version_nonempty",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "database",
                            "config_name",
                            "config_version",
                            "extensions_fingerprint",
                            "catalog_version",
                        ),
                        name="uniq_pool_meta_catalog_snapshot_scope_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("tenant", "database", "config_name", "config_version", "extensions_fingerprint"),
                        name="uniq_pool_meta_catalog_snapshot_scope_current",
                    ),
                ],
            },
        ),
    ]
