# Generated by Django 6.0 on 2026-02-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0015_poolodatametadatacatalogsnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poolodatametadatacatalogsnapshot',
            new_name='pool_odata__tenant__0427c7_idx',
            old_name='pool_odata__tenant__a19468_idx',
        ),
        migrations.RenameIndex(
            model_name='poolodatametadatacatalogsnapshot',
            new_name='pool_odata__tenant__d1783a_idx',
            old_name='pool_odata__tenant__ce5220_idx',
        ),
        migrations.RenameIndex(
            model_name='poolodatametadatacatalogsnapshot',
            new_name='pool_odata__databas_1a7756_idx',
            old_name='pool_odata__databas_2628cd_idx',
        ),
    ]
