# Generated by Django 6.0 on 2026-02-27 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0016_rename_pool_odata__tenant__a19468_idx_pool_odata__tenant__0427c7_idx_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=512)),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('kpp', models.CharField(blank=True, default='', max_length=9)),
                ('is_our_organization', models.BooleanField(default=False)),
                ('is_counterparty', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_parties', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_parties',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_contracts', to='tenancy.tenant')),
                ('owner_counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_pool_master_contracts', to='intercompany_pools.poolmasterparty')),
            ],
            options={
                'db_table': 'pool_master_contracts',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterTaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_included', models.BooleanField(default=True)),
                ('vat_code', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_tax_profiles', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_tax_profiles',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_items', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_items',
                'indexes': [models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__848644_idx'), models.Index(fields=['tenant', 'sku'], name='pool_master_tenant__6452b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'canonical_id'), name='uniq_pool_master_item_tenant_canonical')],
            },
        ),
        migrations.AddIndex(
            model_name='poolmasterparty',
            index=models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__11526e_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterparty',
            index=models.Index(fields=['tenant', 'is_counterparty'], name='pool_master_tenant__edbcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterparty',
            index=models.Index(fields=['tenant', 'is_our_organization'], name='pool_master_tenant__ec0f0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterparty',
            constraint=models.UniqueConstraint(fields=('tenant', 'canonical_id'), name='uniq_pool_master_party_tenant_canonical'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterparty',
            constraint=models.CheckConstraint(condition=models.Q(('is_our_organization', True), ('is_counterparty', True), _connector='OR'), name='chk_pool_master_party_has_role'),
        ),
        migrations.AddIndex(
            model_name='poolmastercontract',
            index=models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__4788f6_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmastercontract',
            index=models.Index(fields=['tenant', 'owner_counterparty'], name='pool_master_tenant__38faf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmastercontract',
            constraint=models.UniqueConstraint(fields=('tenant', 'canonical_id', 'owner_counterparty'), name='uniq_pool_master_contract_tenant_canonical_owner'),
        ),
        migrations.AddIndex(
            model_name='poolmastertaxprofile',
            index=models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__0c744c_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmastertaxprofile',
            index=models.Index(fields=['tenant', 'vat_code'], name='pool_master_tenant__885ac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmastertaxprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'canonical_id'), name='uniq_pool_master_tax_tenant_canonical'),
        ),
        migrations.AddConstraint(
            model_name='poolmastertaxprofile',
            constraint=models.CheckConstraint(condition=models.Q(('vat_rate__gte', 0), ('vat_rate__lte', 100)), name='chk_pool_master_tax_vat_rate_range'),
        ),
    ]
