# Generated by Django 6.0 on 2026-02-27 16:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0017_poolmasterparty_poolmastercontract_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('canonical_id', models.CharField(max_length=128)),
                ('ib_ref_key', models.CharField(max_length=128)),
                ('ib_catalog_kind', models.CharField(blank=True, default='', max_length=32)),
                ('owner_counterparty_canonical_id', models.CharField(blank=True, default='', max_length=128)),
                ('sync_status', models.CharField(choices=[('resolved', 'Resolved'), ('upserted', 'Upserted'), ('conflict', 'Conflict')], db_index=True, default='resolved', max_length=16)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_bindings', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_bindings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_bindings',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'database'], name='pool_master_tenant__ecd1a1_idx'), models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__0ddd30_idx'), models.Index(fields=['tenant', 'sync_status', '-updated_at'], name='pool_master_tenant__da2fe2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ib_ref_key', ''), _negated=True), name='chk_pool_master_binding_ref_nonempty'), models.UniqueConstraint(fields=('tenant', 'entity_type', 'canonical_id', 'database', 'ib_catalog_kind', 'owner_counterparty_canonical_id'), name='uniq_pool_master_binding_scope')],
            },
        ),
    ]
