# Generated by Django 6.0 on 2026-03-02 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0019_organization_master_party'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataSyncScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('policy', models.CharField(choices=[('cc_master', 'CC Master'), ('ib_master', 'IB Master'), ('bidirectional', 'Bidirectional')], db_index=True, default='cc_master', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_scopes', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_scopes', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_scopes',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'database'], name='pool_master_tenant__090553_idx'), models.Index(fields=['tenant', 'policy'], name='pool_master_tenant__010440_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('database__isnull', False)), fields=('tenant', 'entity_type', 'database'), name='uniq_pool_md_sync_scope_db'), models.UniqueConstraint(condition=models.Q(('database__isnull', True)), fields=('tenant', 'entity_type'), name='uniq_pool_md_sync_scope_default')],
            },
        ),
    ]
