# Generated by Django 6.0 on 2026-03-02 18:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0020_poolmasterdatasyncscope'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataSyncCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('error', 'Error')], db_index=True, default='active', max_length=16)),
                ('checkpoint_token', models.CharField(blank=True, default='', max_length=255)),
                ('last_origin_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_checkpoints', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_checkpoints', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_checkpoints',
                'indexes': [models.Index(fields=['tenant', 'status', '-updated_at'], name='pool_master_tenant__c4958e_idx'), models.Index(fields=['tenant', 'database', 'entity_type'], name='pool_master_tenant__eb942d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'database', 'entity_type'), name='uniq_pool_md_sync_checkpoint_scope')],
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataSyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('retrying', 'Retrying'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=16)),
                ('conflict_code', models.CharField(max_length=64)),
                ('canonical_id', models.CharField(blank=True, default='', max_length=128)),
                ('origin_system', models.CharField(blank=True, default='', max_length=32)),
                ('origin_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_conflicts', to='databases.database')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pool_master_data_sync_conflicts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_conflicts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_conflicts',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='pool_master_tenant__9a0e13_idx'), models.Index(fields=['tenant', 'database', 'entity_type', 'status'], name='pool_master_tenant__3683ce_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('conflict_code', ''), _negated=True), name='chk_pool_md_sync_conflict_code_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('policy', models.CharField(choices=[('cc_master', 'CC Master'), ('ib_master', 'IB Master'), ('bidirectional', 'Bidirectional')], default='cc_master', max_length=16)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('workflow_execution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_jobs', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_jobs',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='pool_master_tenant__587241_idx'), models.Index(fields=['tenant', 'database', 'entity_type', 'status'], name='pool_master_tenant__e4ae18_idx')],
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataSyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('dedupe_key', models.CharField(max_length=128)),
                ('origin_system', models.CharField(blank=True, default='cc', max_length=32)),
                ('origin_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_outbox_rows', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_outbox_rows', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_outbox',
                'indexes': [models.Index(fields=['tenant', 'status', 'available_at'], name='pool_master_tenant__f55435_idx'), models.Index(fields=['tenant', 'database', 'entity_type', 'status'], name='pool_master_tenant__a45dc3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), name='chk_pool_md_sync_outbox_dedupe_nonempty'), models.UniqueConstraint(fields=('tenant', 'database', 'entity_type', 'dedupe_key'), name='uniq_pool_md_sync_outbox_scope_dedupe')],
            },
        ),
    ]
