# Generated by Django 6.0 on 2026-03-05 09:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0021_poolmasterdatasynccheckpoint_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataBootstrapImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('preflight_pending', 'Preflight Pending'), ('preflight_failed', 'Preflight Failed'), ('dry_run_pending', 'Dry Run Pending'), ('dry_run_failed', 'Dry Run Failed'), ('execute_pending', 'Execute Pending'), ('running', 'Running'), ('finalized', 'Finalized'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='preflight_pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_bootstrap_import_jobs', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_bootstrap_import_jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_bootstrap_import_jobs',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataBootstrapImportChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('tax_profile', 'Tax Profile'), ('contract', 'Contract'), ('binding', 'Binding')], db_index=True, max_length=32)),
                ('chunk_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='intercompany_pools.poolmasterdatabootstrapimportjob')),
            ],
            options={
                'db_table': 'pool_master_data_bootstrap_import_chunks',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataBootstrapImportReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('deferred_count', models.PositiveIntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='intercompany_pools.poolmasterdatabootstrapimportjob')),
            ],
            options={
                'db_table': 'pool_master_data_bootstrap_import_reports',
            },
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapimportjob',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='pool_master_tenant__1d74d5_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapimportjob',
            index=models.Index(fields=['tenant', 'database', 'status'], name='pool_master_tenant__87ee4c_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapimportchunk',
            index=models.Index(fields=['job', 'status', 'entity_type'], name='pool_master_job_id_98deb4_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapimportchunk',
            index=models.Index(fields=['status', '-updated_at'], name='pool_master_status_503b09_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatabootstrapimportchunk',
            constraint=models.UniqueConstraint(fields=('job', 'entity_type', 'chunk_index'), name='uniq_pool_md_bootstrap_chunk_scope'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapimportreport',
            index=models.Index(fields=['created_at'], name='pool_master_created_e518eb_idx'),
        ),
    ]
