# Generated by Django 6.0 on 2026-03-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0022_poolmasterdatabootstrapimportjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolrun',
            name='runtime_projection_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='poolrun',
            name='workflow_binding_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
