# Generated by Django 6.0 on 2026-03-10 08:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def _backfill_scope_resolutions_and_deduplicate_snapshots(apps, schema_editor):
    snapshot_model = apps.get_model("intercompany_pools", "PoolODataMetadataCatalogSnapshot")
    resolution_model = apps.get_model("intercompany_pools", "PoolODataMetadataCatalogScopeResolution")
    db_alias = schema_editor.connection.alias

    current_snapshots = (
        snapshot_model.objects.using(db_alias)
        .filter(is_current=True)
        .order_by("-fetched_at", "-updated_at", "-created_at", "id")
    )
    for snapshot in current_snapshots.iterator():
        resolution_model.objects.using(db_alias).update_or_create(
            tenant_id=snapshot.tenant_id,
            database_id=snapshot.database_id,
            config_name=snapshot.config_name,
            config_version=snapshot.config_version,
            extensions_fingerprint=snapshot.extensions_fingerprint,
            defaults={
                "snapshot_id": snapshot.id,
                "confirmed_at": snapshot.fetched_at,
            },
        )

    grouped_snapshot_ids: dict[
        tuple[str, str, str, str, str],
        list[uuid.UUID],
    ] = {}
    grouped_snapshots = (
        snapshot_model.objects.using(db_alias)
        .all()
        .order_by("-is_current", "-fetched_at", "-updated_at", "-created_at", "id")
    )
    for snapshot in grouped_snapshots.iterator():
        key = (
            str(snapshot.tenant_id),
            str(snapshot.config_name),
            str(snapshot.config_version),
            str(snapshot.extensions_fingerprint),
            str(snapshot.catalog_version),
        )
        grouped_snapshot_ids.setdefault(key, []).append(snapshot.id)

    for snapshot_ids in grouped_snapshot_ids.values():
        survivor_id = snapshot_ids[0]
        for duplicate_id in snapshot_ids[1:]:
            resolution_model.objects.using(db_alias).filter(snapshot_id=duplicate_id).update(
                snapshot_id=survivor_id
            )
            snapshot_model.objects.using(db_alias).filter(id=duplicate_id).delete()

    resolution_snapshot_ids = set(
        resolution_model.objects.using(db_alias).values_list("snapshot_id", flat=True)
    )
    latest_database_by_snapshot = {}
    latest_resolutions = (
        resolution_model.objects.using(db_alias)
        .order_by("snapshot_id", "-confirmed_at", "-updated_at", "-created_at", "id")
    )
    for resolution in latest_resolutions.iterator():
        latest_database_by_snapshot.setdefault(resolution.snapshot_id, resolution.database_id)

    for snapshot in snapshot_model.objects.using(db_alias).all().iterator():
        updates = {}
        should_be_current = snapshot.id in resolution_snapshot_ids
        if snapshot.is_current != should_be_current:
            updates["is_current"] = should_be_current
        latest_database_id = latest_database_by_snapshot.get(snapshot.id)
        if latest_database_id and snapshot.database_id != latest_database_id:
            updates["database_id"] = latest_database_id
        if updates:
            snapshot_model.objects.using(db_alias).filter(id=snapshot.id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0023_poolrun_runtime_projection_snapshot_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolODataMetadataCatalogScopeResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('config_version', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('extensions_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('confirmed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_odata_metadata_catalog_scope_resolutions',
            },
        ),
        migrations.AddField(
            model_name='poolodatametadatacatalogscoperesolution',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_odata_metadata_catalog_scope_resolutions', to='databases.database'),
        ),
        migrations.AddField(
            model_name='poolodatametadatacatalogscoperesolution',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_resolutions', to='intercompany_pools.poolodatametadatacatalogsnapshot'),
        ),
        migrations.AddField(
            model_name='poolodatametadatacatalogscoperesolution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_odata_metadata_catalog_scope_resolutions', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='poolodatametadatacatalogscoperesolution',
            index=models.Index(fields=['tenant', 'database'], name='pool_odata__tenant__6751d0_idx'),
        ),
        migrations.AddIndex(
            model_name='poolodatametadatacatalogscoperesolution',
            index=models.Index(fields=['tenant', 'config_name', 'config_version', 'extensions_fingerprint'], name='pool_odata__tenant__67809e_idx'),
        ),
        migrations.AddIndex(
            model_name='poolodatametadatacatalogscoperesolution',
            index=models.Index(fields=['snapshot', '-confirmed_at'], name='pool_odata__snapsho_2c2bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolodatametadatacatalogscoperesolution',
            constraint=models.UniqueConstraint(fields=('tenant', 'database', 'config_name', 'config_version', 'extensions_fingerprint'), name='uniq_pool_meta_catalog_scope_resolution'),
        ),
        migrations.RunPython(
            _backfill_scope_resolutions_and_deduplicate_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='poolodatametadatacatalogsnapshot',
            name='uniq_pool_meta_catalog_snapshot_scope_version',
        ),
        migrations.RemoveConstraint(
            model_name='poolodatametadatacatalogsnapshot',
            name='uniq_pool_meta_catalog_snapshot_scope_current',
        ),
        migrations.AddConstraint(
            model_name='poolodatametadatacatalogsnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'config_name', 'config_version', 'extensions_fingerprint', 'catalog_version'), name='uniq_pool_meta_catalog_snapshot_shared_version'),
        ),
    ]
