# Generated by Django 6.0 on 2026-03-10 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0024_poolodatametadatacatalogscoperesolution_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolWorkflowBinding',
            fields=[
                ('binding_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contract_version', models.CharField(default='pool_workflow_binding.v1', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='draft', max_length=16)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('mode', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('selector_tags', models.JSONField(blank=True, default=list)),
                ('workflow_definition_key', models.CharField(db_index=True, max_length=255)),
                ('workflow_revision_id', models.CharField(max_length=255)),
                ('workflow_revision', models.PositiveIntegerField(db_index=True)),
                ('workflow_name', models.CharField(max_length=255)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('role_mapping', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_bindings', to='intercompany_pools.organizationpool')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_workflow_bindings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_workflow_bindings',
                'indexes': [models.Index(fields=['tenant', 'pool', 'status'], name='pool_workfl_tenant__33e951_idx'), models.Index(fields=['tenant', 'pool', 'direction', 'mode', 'status'], name='pool_workfl_tenant__3dad38_idx'), models.Index(fields=['tenant', 'workflow_definition_key', 'workflow_revision'], name='pool_workfl_tenant__ef1fca_idx'), models.Index(fields=['pool', '-updated_at'], name='pool_workfl_pool_id_badf70_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('binding_id', ''), _negated=True), name='chk_pool_workflow_binding_binding_id_nonempty'), models.CheckConstraint(condition=models.Q(('workflow_definition_key', ''), _negated=True), name='chk_pool_workflow_binding_definition_key_nonempty'), models.CheckConstraint(condition=models.Q(('workflow_revision_id', ''), _negated=True), name='chk_pool_workflow_binding_revision_id_nonempty'), models.CheckConstraint(condition=models.Q(('workflow_name', ''), _negated=True), name='chk_pool_workflow_binding_workflow_name_nonempty'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_pool_workflow_binding_effective_range')],
            },
        ),
    ]
