# Generated by Django 6.0 on 2026-03-17 10:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0026_business_identity_scope_without_extensions_fingerprint'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('deactivated_by', models.CharField(blank=True, default='', max_length=255)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_profiles', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'binding_profiles',
            },
        ),
        migrations.CreateModel(
            name='BindingProfileRevision',
            fields=[
                ('binding_profile_revision_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contract_version', models.CharField(default='binding_profile_revision.v1', max_length=64)),
                ('revision_number', models.PositiveIntegerField()),
                ('workflow_definition_key', models.CharField(db_index=True, max_length=255)),
                ('workflow_revision_id', models.CharField(max_length=255)),
                ('workflow_revision', models.PositiveIntegerField(db_index=True)),
                ('workflow_name', models.CharField(max_length=255)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('role_mapping', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intercompany_pools.bindingprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_profile_revisions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'binding_profile_revisions',
            },
        ),
        migrations.AddIndex(
            model_name='bindingprofile',
            index=models.Index(fields=['tenant', 'status'], name='binding_pro_tenant__5f4ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='bindingprofile',
            index=models.Index(fields=['tenant', '-updated_at'], name='binding_pro_tenant__a11c91_idx'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_binding_profile_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='chk_binding_profile_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_binding_profile_name_nonempty'),
        ),
        migrations.AddIndex(
            model_name='bindingprofilerevision',
            index=models.Index(fields=['tenant', 'profile', '-revision_number'], name='binding_pro_tenant__040280_idx'),
        ),
        migrations.AddIndex(
            model_name='bindingprofilerevision',
            index=models.Index(fields=['tenant', 'workflow_definition_key', 'workflow_revision'], name='binding_pro_tenant__ae3603_idx'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofilerevision',
            constraint=models.UniqueConstraint(fields=('profile', 'revision_number'), name='uniq_binding_profile_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofilerevision',
            constraint=models.CheckConstraint(condition=models.Q(('binding_profile_revision_id', ''), _negated=True), name='chk_binding_profile_revision_id_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofilerevision',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_definition_key', ''), _negated=True), name='chk_binding_profile_revision_definition_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofilerevision',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_revision_id', ''), _negated=True), name='chk_binding_profile_revision_workflow_revision_id_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='bindingprofilerevision',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_name', ''), _negated=True), name='chk_binding_profile_revision_workflow_name_nonempty'),
        ),
    ]
