# Generated by Django 6.0 on 2026-03-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0027_bindingprofile_bindingprofilerevision_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolworkflowbinding',
            name='binding_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_attachments', to='intercompany_pools.bindingprofile'),
        ),
        migrations.AddField(
            model_name='poolworkflowbinding',
            name='binding_profile_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_attachments', to='intercompany_pools.bindingprofilerevision'),
        ),
        migrations.AddIndex(
            model_name='poolworkflowbinding',
            index=models.Index(fields=['tenant', 'pool', 'binding_profile_revision'], name='pool_workfl_tenant__cdcf96_idx'),
        ),
    ]
