# Generated by Django 6.0 on 2026-03-22 18:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0028_poolworkflowbinding_binding_profile_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_templates', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'topology_templates',
            },
        ),
        migrations.CreateModel(
            name='TopologyTemplateRevision',
            fields=[
                ('topology_template_revision_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contract_version', models.CharField(default='topology_template_revision.v1', max_length=64)),
                ('revision_number', models.PositiveIntegerField()),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intercompany_pools.topologytemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_template_revisions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'topology_template_revisions',
            },
        ),
        migrations.AddIndex(
            model_name='topologytemplate',
            index=models.Index(fields=['tenant', 'status'], name='topology_te_tenant__b67e63_idx'),
        ),
        migrations.AddIndex(
            model_name='topologytemplate',
            index=models.Index(fields=['tenant', '-updated_at'], name='topology_te_tenant__6a24ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='topologytemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_topology_template_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='topologytemplate',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='chk_topology_template_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='topologytemplate',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_topology_template_name_nonempty'),
        ),
        migrations.AddIndex(
            model_name='topologytemplaterevision',
            index=models.Index(fields=['tenant', 'template', '-revision_number'], name='topology_te_tenant__cca283_idx'),
        ),
        migrations.AddConstraint(
            model_name='topologytemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'revision_number'), name='uniq_topology_template_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='topologytemplaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('topology_template_revision_id', ''), _negated=True), name='chk_topology_template_revision_id_nonempty'),
        ),
    ]
