# Generated by Django 6.0 on 2026-03-25 08:00

from django.db import migrations


MIGRATION_ACTOR_USERNAME = "system:migrate-top-down-execution-pack-aliases"


def _adopt_existing_top_down_execution_pack_aliases(apps, schema_editor):
    from apps.intercompany_pools.top_down_execution_pack_alias_adoption import (
        adopt_top_down_execution_pack_aliases_for_all_tenants,
    )

    adopt_top_down_execution_pack_aliases_for_all_tenants(
        actor_username=MIGRATION_ACTOR_USERNAME,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("intercompany_pools", "0029_topologytemplate_topologytemplaterevision_and_more"),
        ("templates", "0027_decisiontable_source_provenance"),
    ]

    operations = [
        migrations.RunPython(
            _adopt_existing_top_down_execution_pack_aliases,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
