# Generated by Django 6.0 on 2026-03-27 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0030_adopt_top_down_execution_pack_aliases'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_kind', models.CharField(choices=[('receipt', 'Receipt'), ('sale', 'Sale')], db_index=True, max_length=16)),
                ('source_type', models.CharField(choices=[('schema_template_upload', 'Schema Template Upload'), ('integration', 'Integration'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload_ref', models.CharField(blank=True, default='', max_length=512)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('normalization_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='intercompany_pools.organizationpool')),
                ('run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_batch', to='intercompany_pools.poolrun')),
                ('schema_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='intercompany_pools.poolschematemplate')),
                ('start_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_batches_started', to='intercompany_pools.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_batches', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_batches',
            },
        ),
        migrations.CreateModel(
            name='PoolBatchSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ingested', 'Ingested'), ('distributed', 'Distributed'), ('partially_closed', 'Partially Closed'), ('closed', 'Closed'), ('carried_forward', 'Carried Forward'), ('attention_required', 'Attention Required')], db_index=True, default='ingested', max_length=32)),
                ('incoming_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outgoing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('freshness_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='intercompany_pools.poolbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_batch_settlements', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_batch_settlements',
            },
        ),
        migrations.CreateModel(
            name='PoolFactualBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter_start', models.DateField(db_index=True)),
                ('quarter_end', models.DateField(db_index=True)),
                ('amount_with_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_without_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('incoming_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outgoing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('freshness_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factual_balance_snapshots', to='intercompany_pools.poolbatch')),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factual_balance_snapshots', to='intercompany_pools.pooledgeversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_balance_snapshots', to='intercompany_pools.organization')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_balance_snapshots', to='intercompany_pools.organizationpool')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_factual_balance_snapshots', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_factual_balance_snapshots',
            },
        ),
        migrations.CreateModel(
            name='PoolFactualReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter_start', models.DateField(db_index=True)),
                ('quarter_end', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('unattributed', 'Unattributed'), ('late_correction', 'Late Correction')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attributed', 'Attributed'), ('reconciled', 'Reconciled'), ('resolved_without_change', 'Resolved Without Change')], db_index=True, default='pending', max_length=32)),
                ('source_document_ref', models.CharField(blank=True, default='', max_length=512)),
                ('delta_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factual_review_items', to='intercompany_pools.poolbatch')),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factual_review_items', to='intercompany_pools.pooledgeversion')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factual_review_items', to='intercompany_pools.organization')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_review_items', to='intercompany_pools.organizationpool')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pool_factual_review_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_factual_review_items', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_factual_review_items',
            },
        ),
        migrations.CreateModel(
            name='PoolFactualSyncCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane', models.CharField(choices=[('read', 'Read'), ('reconcile', 'Reconcile')], db_index=True, max_length=16)),
                ('quarter_start', models.DateField(db_index=True)),
                ('quarter_end', models.DateField(db_index=True)),
                ('source_checkpoint_token', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factual_sync_checkpoints', to='intercompany_pools.poolbatch')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_factual_sync_checkpoints', to='databases.database')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_sync_checkpoints', to='intercompany_pools.organizationpool')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_factual_sync_checkpoints', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_factual_sync_checkpoints',
            },
        ),
        migrations.AddIndex(
            model_name='poolbatch',
            index=models.Index(fields=['tenant', 'pool', 'period_start'], name='pool_batche_tenant__2023b3_idx'),
        ),
        migrations.AddIndex(
            model_name='poolbatch',
            index=models.Index(fields=['tenant', 'batch_kind', '-created_at'], name='pool_batche_tenant__8b7ae6_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolbatch',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='chk_pool_batch_period_range'),
        ),
        migrations.AddIndex(
            model_name='poolbatchsettlement',
            index=models.Index(fields=['tenant', 'status', '-updated_at'], name='pool_batch__tenant__372905_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualbalancesnapshot',
            index=models.Index(fields=['tenant', 'pool', 'quarter_start'], name='pool_factua_tenant__6b7472_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualbalancesnapshot',
            index=models.Index(fields=['tenant', 'organization', 'quarter_start'], name='pool_factua_tenant__7b5fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualbalancesnapshot',
            index=models.Index(fields=['tenant', 'batch', 'quarter_start'], name='pool_factua_tenant__188699_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolfactualbalancesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('quarter_end__gte', models.F('quarter_start'))), name='chk_pool_factual_balance_quarter_range'),
        ),
        migrations.AddIndex(
            model_name='poolfactualreviewitem',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='pool_factua_tenant__8bbf68_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualreviewitem',
            index=models.Index(fields=['tenant', 'reason', '-created_at'], name='pool_factua_tenant__a604cd_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualreviewitem',
            index=models.Index(fields=['tenant', 'pool', 'quarter_start'], name='pool_factua_tenant__b9a7bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolfactualreviewitem',
            constraint=models.CheckConstraint(condition=models.Q(('quarter_end__gte', models.F('quarter_start'))), name='chk_pool_factual_review_quarter_range'),
        ),
        migrations.AddIndex(
            model_name='poolfactualsynccheckpoint',
            index=models.Index(fields=['tenant', 'lane', 'quarter_start'], name='pool_factua_tenant__60d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualsynccheckpoint',
            index=models.Index(fields=['tenant', 'database', 'lane'], name='pool_factua_tenant__f42f4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolfactualsynccheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('quarter_end__gte', models.F('quarter_start'))), name='chk_pool_factual_checkpoint_quarter_range'),
        ),
    ]
