# Generated by Django 6.0 on 2026-03-28 11:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0029_extensionflagspolicy"),
        ("intercompany_pools", "0031_poolbatch_poolbatchsettlement_and_more"),
        ("tenancy", "0003_alter_tenant_options_alter_tenantmember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolbatch",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="poolbatch",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="poolbatch",
            name="operation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="poolbatch",
            name="publication_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="poolbatch",
            name="workflow_execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="poolbatch",
            name="workflow_status",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="PoolBatchPublicationAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_name", models.CharField(max_length=255)),
                ("documents_count", models.PositiveIntegerField(default=1)),
                ("external_document_identity", models.CharField(blank=True, default="", max_length=128)),
                ("identity_strategy", models.CharField(blank=True, default="", max_length=64)),
                ("posted", models.BooleanField(default=False)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("request_summary", models.JSONField(blank=True, default=dict)),
                ("response_summary", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_attempts",
                        to="intercompany_pools.poolbatch",
                    ),
                ),
                (
                    "target_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pool_batch_publication_attempts",
                        to="databases.database",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_batch_publication_attempts",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pool_batch_publication_attempts",
            },
        ),
        migrations.AddIndex(
            model_name="poolbatchpublicationattempt",
            index=models.Index(
                fields=["batch", "status", "-created_at"],
                name="pool_batch_batch_id_f54f35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="poolbatchpublicationattempt",
            index=models.Index(
                fields=["target_database", "status", "-created_at"],
                name="pool_batch_target__460208_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="poolbatchpublicationattempt",
            constraint=models.UniqueConstraint(
                fields=("batch", "target_database", "attempt_number"),
                name="uniq_pool_batch_publication_attempt_per_target",
            ),
        ),
    ]
