# Generated by Django 6.0 on 2026-03-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0033_poolfactualsynccheckpoint_workflow_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poolbatchpublicationattempt',
            new_name='pool_batch__batch_i_707ab1_idx',
            old_name='pool_batch_batch_id_f54f35_idx',
        ),
        migrations.RenameIndex(
            model_name='poolbatchpublicationattempt',
            new_name='pool_batch__target__200081_idx',
            old_name='pool_batch_target__460208_idx',
        ),
    ]
