# Generated by Django 6.0 on 2026-04-04 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0034_rename_pool_batch_batch_id_f54f35_idx_pool_batch__batch_i_707ab1_idx_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterGLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('chart_identity', models.CharField(max_length=255)),
                ('config_name', models.CharField(max_length=255)),
                ('config_version', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_gl_accounts',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterGLAccountSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('chart_identity', models.CharField(max_length=255)),
                ('config_name', models.CharField(max_length=255)),
                ('config_version', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_gl_account_sets',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterGLAccountSetDraftMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_gl_account_set_draft_members',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterGLAccountSetRevision',
            fields=[
                ('gl_account_set_revision_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contract_version', models.CharField(default='gl_account_set_revision.v1', max_length=64)),
                ('revision_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('chart_identity', models.CharField(max_length=255)),
                ('config_name', models.CharField(max_length=255)),
                ('config_version', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pool_master_gl_account_set_revisions',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterGLAccountSetRevisionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gl_account_canonical_id', models.CharField(max_length=128)),
                ('gl_account_code', models.CharField(max_length=128)),
                ('gl_account_name', models.CharField(max_length=255)),
                ('chart_identity', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pool_master_gl_account_set_revision_members',
            },
        ),
        migrations.RemoveConstraint(
            model_name='poolmasterdatabinding',
            name='uniq_pool_master_binding_scope',
        ),
        migrations.AddField(
            model_name='poolmasterdatabinding',
            name='chart_identity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='poolmasterdatabinding',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatabootstrapimportchunk',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('contract', 'Contract'), ('binding', 'Binding')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatasynccheckpoint',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatasyncconflict',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatasyncjob',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatasyncoutbox',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='poolmasterdatasyncscope',
            name='entity_type',
            field=models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabinding',
            index=models.Index(fields=['tenant', 'chart_identity'], name='pool_master_tenant__ed3730_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatabinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'entity_type', 'canonical_id', 'database', 'ib_catalog_kind', 'owner_counterparty_canonical_id', 'chart_identity'), name='uniq_pool_master_binding_scope'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_gl_accounts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_gl_account_sets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetdraftmember',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_account_set_draft_memberships', to='intercompany_pools.poolmasterglaccount'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetdraftmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_members', to='intercompany_pools.poolmasterglaccountset'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetdraftmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_gl_account_set_draft_members', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetrevision',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intercompany_pools.poolmasterglaccountset'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetrevision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_gl_account_set_revisions', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountset',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for_sets', to='intercompany_pools.poolmasterglaccountsetrevision'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetrevisionmember',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_account_set_revision_memberships', to='intercompany_pools.poolmasterglaccount'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetrevisionmember',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='intercompany_pools.poolmasterglaccountsetrevision'),
        ),
        migrations.AddField(
            model_name='poolmasterglaccountsetrevisionmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_gl_account_set_revision_members', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccount',
            index=models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__c4f9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccount',
            index=models.Index(fields=['tenant', 'chart_identity'], name='pool_master_tenant__6b7ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccount',
            index=models.Index(fields=['tenant', 'config_name', 'config_version'], name='pool_master_tenant__662d72_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'canonical_id'), name='uniq_pool_master_gl_account_tenant_canonical'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='chk_pool_master_gl_account_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_pool_master_gl_account_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.CheckConstraint(condition=models.Q(('chart_identity', ''), _negated=True), name='chk_pool_master_gl_account_chart_identity_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.CheckConstraint(condition=models.Q(('config_name', ''), _negated=True), name='chk_pool_master_gl_account_config_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccount',
            constraint=models.CheckConstraint(condition=models.Q(('config_version', ''), _negated=True), name='chk_pool_master_gl_account_config_version_nonempty'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetdraftmember',
            index=models.Index(fields=['tenant', 'profile', 'sort_order'], name='pool_master_tenant__bec719_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetdraftmember',
            index=models.Index(fields=['tenant', 'gl_account'], name='pool_master_tenant__109557_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetdraftmember',
            constraint=models.UniqueConstraint(fields=('profile', 'gl_account'), name='uniq_pool_master_gl_account_set_draft_member'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetdraftmember',
            constraint=models.UniqueConstraint(fields=('profile', 'sort_order'), name='uniq_pool_master_gl_account_set_draft_sort'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetrevision',
            index=models.Index(fields=['tenant', 'profile', '-revision_number'], name='pool_master_tenant__112b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetrevision',
            index=models.Index(fields=['tenant', 'chart_identity'], name='pool_master_tenant__55445b_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetrevision',
            index=models.Index(fields=['tenant', 'config_name', 'config_version'], name='pool_master_tenant__377484_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.UniqueConstraint(fields=('profile', 'revision_number'), name='uniq_pool_master_gl_account_set_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('gl_account_set_revision_id', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_id_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('chart_identity', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_chart_identity_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('config_name', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_config_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('config_version', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_config_version_nonempty'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountset',
            index=models.Index(fields=['tenant', 'canonical_id'], name='pool_master_tenant__45d76a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountset',
            index=models.Index(fields=['tenant', 'chart_identity'], name='pool_master_tenant__0eda7e_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountset',
            index=models.Index(fields=['tenant', 'config_name', 'config_version'], name='pool_master_tenant__ace9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountset',
            index=models.Index(fields=['tenant', '-updated_at'], name='pool_master_tenant__25893b_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.UniqueConstraint(fields=('tenant', 'canonical_id'), name='uniq_pool_master_gl_account_set_tenant_canonical'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_id', ''), _negated=True), name='chk_pool_master_gl_account_set_canonical_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chk_pool_master_gl_account_set_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.CheckConstraint(condition=models.Q(('chart_identity', ''), _negated=True), name='chk_pool_master_gl_account_set_chart_identity_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.CheckConstraint(condition=models.Q(('config_name', ''), _negated=True), name='chk_pool_master_gl_account_set_config_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountset',
            constraint=models.CheckConstraint(condition=models.Q(('config_version', ''), _negated=True), name='chk_pool_master_gl_account_set_config_version_nonempty'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetrevisionmember',
            index=models.Index(fields=['tenant', 'revision', 'sort_order'], name='pool_master_tenant__a4e37a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccountsetrevisionmember',
            index=models.Index(fields=['tenant', 'gl_account_canonical_id'], name='pool_master_tenant__5e89d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.UniqueConstraint(fields=('revision', 'gl_account_canonical_id'), name='uniq_pool_master_gl_account_set_revision_member_canonical'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.UniqueConstraint(fields=('revision', 'sort_order'), name='uniq_pool_master_gl_account_set_revision_member_sort'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.CheckConstraint(condition=models.Q(('gl_account_canonical_id', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_member_canonical_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.CheckConstraint(condition=models.Q(('gl_account_code', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_member_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.CheckConstraint(condition=models.Q(('gl_account_name', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_member_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterglaccountsetrevisionmember',
            constraint=models.CheckConstraint(condition=models.Q(('chart_identity', ''), _negated=True), name='chk_pool_master_gl_account_set_revision_member_chart_identity_nonempty'),
        ),
    ]
