# Generated by Django 6.0 on 2026-04-04 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0035_poolmasterglaccount_poolmasterglaccountset_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFactualScopeSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_profile', models.CharField(db_index=True, max_length=64)),
                ('quarter_start', models.DateField(db_index=True)),
                ('quarter_end', models.DateField(db_index=True)),
                ('selection_mode', models.CharField(db_index=True, default='system_managed', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_factual_scope_selections',
            },
        ),
        migrations.AddField(
            model_name='poolfactualsynccheckpoint',
            name='scope_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='poolfactualsynccheckpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_fingerprint', ''), _negated=True), fields=('tenant', 'pool', 'database', 'lane', 'quarter_start', 'scope_fingerprint'), name='uniq_pool_factual_checkpoint_scope_fingerprint'),
        ),
        migrations.AddField(
            model_name='poolfactualscopeselection',
            name='gl_account_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_scope_selections', to='intercompany_pools.poolmasterglaccountset'),
        ),
        migrations.AddField(
            model_name='poolfactualscopeselection',
            name='gl_account_set_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factual_scope_selections', to='intercompany_pools.poolmasterglaccountsetrevision'),
        ),
        migrations.AddField(
            model_name='poolfactualscopeselection',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factual_scope_selections', to='intercompany_pools.organizationpool'),
        ),
        migrations.AddField(
            model_name='poolfactualscopeselection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_factual_scope_selections', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='poolfactualscopeselection',
            index=models.Index(fields=['tenant', 'pool', 'source_profile', 'quarter_start'], name='pool_factua_tenant__d6892a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolfactualscopeselection',
            index=models.Index(fields=['tenant', 'gl_account_set_revision'], name='pool_factua_tenant__fa23a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolfactualscopeselection',
            constraint=models.CheckConstraint(condition=models.Q(('quarter_end__gte', models.F('quarter_start'))), name='chk_pool_factual_scope_selection_quarter_range'),
        ),
        migrations.AddConstraint(
            model_name='poolfactualscopeselection',
            constraint=models.UniqueConstraint(fields=('tenant', 'pool', 'source_profile', 'quarter_start'), name='uniq_pool_factual_scope_selection'),
        ),
    ]
