# Generated by Django 6.0 on 2026-04-11 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0036_poolfactualscopeselection_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataBootstrapCollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_mode', models.CharField(choices=[('cluster_all', 'Cluster All'), ('database_set', 'Database Set')], db_index=True, max_length=32)),
                ('mode', models.CharField(choices=[('dry_run', 'Dry Run'), ('execute', 'Execute')], db_index=True, max_length=16)),
                ('cluster_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('database_ids', models.JSONField(blank=True, default=list)),
                ('entity_scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('dry_run_completed', 'Dry Run Completed'), ('execute_running', 'Execute Running'), ('finalized', 'Finalized'), ('failed', 'Failed')], db_index=True, default='dry_run_completed', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pool_master_data_bootstrap_collections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_bootstrap_collection_requests', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_bootstrap_collections',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataBootstrapCollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('coalesced', 'Coalesced'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='completed', max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='intercompany_pools.poolmasterdatabootstrapimportjob')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_bootstrap_collection_items', to='databases.database')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intercompany_pools.poolmasterdatabootstrapcollectionrequest')),
            ],
            options={
                'db_table': 'pool_master_data_bootstrap_collection_items',
            },
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapcollectionrequest',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='pool_master_tenant__f91944_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapcollectionrequest',
            index=models.Index(fields=['tenant', 'target_mode', '-created_at'], name='pool_master_tenant__7e011b_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapcollectionitem',
            index=models.Index(fields=['collection', 'status'], name='pool_master_collect_db6c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatabootstrapcollectionitem',
            index=models.Index(fields=['database', 'status'], name='pool_master_databas_ce82d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatabootstrapcollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'database'), name='uniq_pool_md_bootstrap_collection_item_scope'),
        ),
    ]
