# Generated by Django 6.0 on 2026-04-11 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0037_poolmasterdatabootstrapcollectionrequest_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataDedupeCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('canonical_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('resolved_auto', 'Resolved Auto'), ('resolved_manual', 'Resolved Manual'), ('pending_review', 'Pending Review'), ('superseded', 'Superseded')], db_index=True, default='resolved_auto', max_length=32)),
                ('rollout_eligible', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('normalized_signals', models.JSONField(blank=True, default=dict)),
                ('conflicting_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pool_master_data_dedupe_clusters', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_dedupe_clusters', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_dedupe_clusters',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32)),
                ('source_ref', models.CharField(max_length=255)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('source_canonical_id', models.CharField(blank=True, default='', max_length=128)),
                ('canonical_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('origin_kind', models.CharField(blank=True, default='bootstrap_import', max_length=32)),
                ('origin_ref', models.CharField(blank=True, default='', max_length=128)),
                ('resolution_status', models.CharField(choices=[('ingested', 'Ingested'), ('resolved_auto', 'Resolved Auto'), ('resolved_manual', 'Resolved Manual'), ('pending_review', 'Pending Review')], db_index=True, default='ingested', max_length=32)),
                ('resolution_reason', models.CharField(blank=True, default='', max_length=64)),
                ('normalized_signals', models.JSONField(blank=True, default=dict)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='intercompany_pools.poolmasterdatadedupecluster')),
                ('source_database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_source_records', to='databases.database')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_source_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_source_records',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataDedupeReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('resolved_auto', 'Resolved Auto'), ('resolved_manual', 'Resolved Manual'), ('superseded', 'Superseded')], db_index=True, default='pending_review', max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('conflicting_fields', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='intercompany_pools.poolmasterdatadedupecluster')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pool_master_data_dedupe_review_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_dedupe_review_items', to='tenancy.tenant')),
                ('proposed_survivor_source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_dedupe_review_items', to='intercompany_pools.poolmasterdatasourcerecord')),
            ],
            options={
                'db_table': 'pool_master_data_dedupe_review_items',
            },
        ),
        migrations.AddIndex(
            model_name='poolmasterdatadedupecluster',
            index=models.Index(fields=['tenant', 'entity_type', 'status'], name='pool_master_tenant__d4f6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatadedupecluster',
            index=models.Index(fields=['tenant', 'entity_type', 'dedupe_key'], name='pool_master_tenant__48bccb_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatadedupecluster',
            index=models.Index(fields=['tenant', 'entity_type', 'canonical_id'], name='pool_master_tenant__3c2c50_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatadedupecluster',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_id__isnull', False)), fields=('tenant', 'entity_type', 'canonical_id'), name='uniq_pool_md_dedupe_cluster_canonical'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasourcerecord',
            index=models.Index(fields=['tenant', 'entity_type', 'resolution_status'], name='pool_master_tenant__6a49ef_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasourcerecord',
            index=models.Index(fields=['tenant', 'entity_type', 'canonical_id'], name='pool_master_tenant__83043a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasourcerecord',
            index=models.Index(fields=['tenant', 'entity_type', 'source_fingerprint'], name='pool_master_tenant__ea1f07_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatasourcerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_database__isnull', False)), fields=('tenant', 'entity_type', 'source_database', 'source_ref'), name='uniq_pool_md_source_record_db_ref'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatadedupereviewitem',
            index=models.Index(fields=['tenant', 'entity_type', 'status'], name='pool_master_tenant__8defa1_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatadedupereviewitem',
            index=models.Index(fields=['tenant', 'reason_code', '-created_at'], name='pool_master_tenant__b75477_idx'),
        ),
    ]
