# Generated by Django 6.0 on 2026-04-11 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0038_poolmasterdatadedupecluster_and_more'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataSyncLaunchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('reconcile', 'Reconcile')], db_index=True, max_length=16)),
                ('target_mode', models.CharField(choices=[('cluster_all', 'Cluster All'), ('database_set', 'Database Set')], db_index=True, max_length=32)),
                ('cluster_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('database_ids', models.JSONField(blank=True, default=list)),
                ('entity_scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('workflow_execution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pool_master_data_sync_launches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_sync_launch_requests', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pool_master_data_sync_launch_requests',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataSyncLaunchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('party', 'Party'), ('item', 'Item'), ('contract', 'Contract'), ('tax_profile', 'Tax Profile'), ('gl_account', 'GL Account'), ('gl_account_set', 'GL Account Set')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('coalesced', 'Coalesced'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_items', to='intercompany_pools.poolmasterdatasyncjob')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_sync_launch_items', to='databases.database')),
                ('launch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intercompany_pools.poolmasterdatasynclaunchrequest')),
            ],
            options={
                'db_table': 'pool_master_data_sync_launch_items',
            },
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasynclaunchrequest',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='pool_master_tenant__1eec82_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasynclaunchrequest',
            index=models.Index(fields=['tenant', 'mode', '-created_at'], name='pool_master_tenant__ab8352_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasynclaunchrequest',
            index=models.Index(fields=['tenant', 'target_mode', '-created_at'], name='pool_master_tenant__af362e_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasynclaunchitem',
            index=models.Index(fields=['launch_request', 'status'], name='pool_master_launch__2dd10b_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatasynclaunchitem',
            index=models.Index(fields=['database', 'entity_type', 'status'], name='pool_master_databas_75f69b_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatasynclaunchitem',
            constraint=models.UniqueConstraint(fields=('launch_request', 'database', 'entity_type'), name='uniq_pool_md_sync_launch_item_scope'),
        ),
    ]
