# Generated by Django 6.0 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intercompany_pools", "0039_poolmasterdatasynclaunchrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poolmasterdatabootstrapcollectionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("coalesced", "Coalesced"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="completed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="poolmasterdatabootstrapcollectionrequest",
            name="mode",
            field=models.CharField(
                choices=[
                    ("preflight", "Preflight"),
                    ("dry_run", "Dry Run"),
                    ("execute", "Execute"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="poolmasterdatabootstrapcollectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("preflight_completed", "Preflight Completed"),
                    ("dry_run_completed", "Dry Run Completed"),
                    ("dry_run_running", "Dry Run Running"),
                    ("execute_running", "Execute Running"),
                    ("finalized", "Finalized"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="dry_run_completed",
                max_length=32,
            ),
        ),
    ]
