# Generated by Django 6.0 on 2026-04-22 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_extensionflagspolicy'),
        ('intercompany_pools', '0040_alter_poolmasterdatabootstrapcollection_fields'),
        ('tenancy', '0003_alter_tenant_options_alter_tenantmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMasterDataChartFollowerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('ok', 'OK'), ('backfilled', 'Backfilled'), ('missing', 'Missing'), ('ambiguous', 'Ambiguous'), ('stale', 'Stale')], db_index=True, max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('matched_accounts', models.IntegerField(default=0)),
                ('missing_accounts', models.IntegerField(default=0)),
                ('ambiguous_accounts', models.IntegerField(default=0)),
                ('stale_bindings', models.IntegerField(default=0)),
                ('backfilled_accounts', models.IntegerField(default=0)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_data_chart_follower_statuses',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataChartMaterializationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('preflight', 'Preflight'), ('dry_run', 'Dry Run'), ('materialize', 'Materialize'), ('verify_followers', 'Verify Followers'), ('backfill_bindings', 'Backfill Bindings')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('database_ids', models.JSONField(blank=True, default=list)),
                ('requested_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.TextField(blank=True, default='')),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_data_chart_jobs',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataChartSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=128)),
                ('row_count', models.IntegerField(default=0)),
                ('materialized_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('unchanged_count', models.IntegerField(default=0)),
                ('retired_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pool_master_data_chart_snapshots',
            },
        ),
        migrations.CreateModel(
            name='PoolMasterDataChartSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_identity', models.CharField(max_length=255)),
                ('config_name', models.CharField(max_length=255)),
                ('config_version', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error')], db_index=True, default='active', max_length=16)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pool_master_data_chart_sources',
            },
        ),
        migrations.AddField(
            model_name='poolmasterglaccount',
            name='is_retired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='poolmasterglaccount',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='poolmasterglaccount',
            index=models.Index(fields=['tenant', 'is_retired'], name='pool_master_tenant__15b93e_idx'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartfollowerstatus',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_chart_follower_statuses', to='databases.database'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartfollowerstatus',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_chart_follower_statuses', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartmaterializationjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_chart_jobs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartfollowerstatus',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_statuses', to='intercompany_pools.poolmasterdatachartmaterializationjob'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_chart_snapshots', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartmaterializationjob',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='intercompany_pools.poolmasterdatachartsnapshot'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartfollowerstatus',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower_statuses', to='intercompany_pools.poolmasterdatachartsnapshot'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartsource',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_master_data_chart_sources', to='databases.database'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartsource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_master_data_chart_sources', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartsnapshot',
            name='chart_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intercompany_pools.poolmasterdatachartsource'),
        ),
        migrations.AddField(
            model_name='poolmasterdatachartmaterializationjob',
            name='chart_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='intercompany_pools.poolmasterdatachartsource'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartfollowerstatus',
            index=models.Index(fields=['tenant', 'database', 'verdict'], name='pool_master_tenant__bae8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartfollowerstatus',
            index=models.Index(fields=['tenant', 'job', 'database'], name='pool_master_tenant__d377ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartfollowerstatus',
            constraint=models.UniqueConstraint(fields=('job', 'database'), name='uniq_pool_master_data_chart_follower_status_job_database'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsource',
            index=models.Index(fields=['tenant', 'chart_identity'], name='pool_master_tenant__ffa16a_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsource',
            index=models.Index(fields=['tenant', 'config_name', 'config_version'], name='pool_master_tenant__de45c2_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsource',
            index=models.Index(fields=['tenant', 'database'], name='pool_master_tenant__2d9280_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsource',
            index=models.Index(fields=['tenant', 'status'], name='pool_master_tenant__a6c38e_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartsource',
            constraint=models.UniqueConstraint(fields=('tenant', 'chart_identity', 'config_name', 'config_version'), name='uniq_pool_master_data_chart_source_compatibility'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartsource',
            constraint=models.CheckConstraint(condition=models.Q(('chart_identity', ''), _negated=True), name='chk_pool_master_data_chart_source_chart_identity_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartsource',
            constraint=models.CheckConstraint(condition=models.Q(('config_name', ''), _negated=True), name='chk_pool_master_data_chart_source_config_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartsource',
            constraint=models.CheckConstraint(condition=models.Q(('config_version', ''), _negated=True), name='chk_pool_master_data_chart_source_config_version_nonempty'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsnapshot',
            index=models.Index(fields=['tenant', 'chart_source', '-created_at'], name='pool_master_tenant__1e993d_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartsnapshot',
            index=models.Index(fields=['tenant', 'fingerprint'], name='pool_master_tenant__ddf268_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolmasterdatachartsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('fingerprint', ''), _negated=True), name='chk_pool_master_data_chart_snapshot_fingerprint_nonempty'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartmaterializationjob',
            index=models.Index(fields=['tenant', 'chart_source', '-created_at'], name='pool_master_tenant__f0bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='poolmasterdatachartmaterializationjob',
            index=models.Index(fields=['tenant', 'mode', 'status'], name='pool_master_tenant__c42c3b_idx'),
        ),
    ]
