# Generated by Django 6.0 on 2026-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercompany_pools', '0041_poolmasterdatachartfollowerstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolbatch',
            name='source_type',
            field=models.CharField(choices=[('schema_template_upload', 'Schema Template Upload'), ('kvo17_generated_purchase', 'KVO17 Generated Purchase'), ('integration', 'Integration'), ('manual', 'Manual')], db_index=True, max_length=32),
        ),
    ]
