# Generated by Django 4.2.25 on 2025-12-09 19:47

import apps.files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Stored filename (sanitized)', max_length=255)),
                ('original_filename', models.CharField(help_text='Original filename from upload', max_length=255)),
                ('file_path', models.CharField(help_text='Relative path in storage directory', max_length=500)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of file', max_length=100)),
                ('purpose', models.CharField(choices=[('operation_input', 'Operation Input'), ('extension', 'Extension File'), ('export', 'Export File')], help_text='Purpose of the file', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.files.models.get_default_expires_at, help_text='Auto-delete after this time')),
                ('is_processed', models.BooleanField(default=False, help_text='File has been processed by operation')),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of file', max_length=64)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='uploaded_fi_expires_8df13c_idx'), models.Index(fields=['purpose', 'created_at'], name='uploaded_fi_purpose_450655_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='uploaded_fi_uploade_791330_idx'), models.Index(fields=['is_processed'], name='uploaded_fi_is_proc_783377_idx')],
            },
        ),
    ]
