# Generated by Django 4.2.25 on 2025-12-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['checksum'], name='uploaded_fi_checksu_37ec2f_idx'),
        ),
    ]
