# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_seed_default_tenant"),
        ("runtime_settings", "0003_seed_ui_action_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantRuntimeSettingOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=128)),
                ("value", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runtime_setting_overrides", to="tenancy.tenant")),
            ],
            options={
                "db_table": "tenant_runtime_setting_overrides",
                "ordering": ["tenant_id", "key"],
                "unique_together": {("tenant", "key")},
                "verbose_name": "Tenant Runtime Setting Override",
                "verbose_name_plural": "Tenant Runtime Setting Overrides",
            },
        ),
    ]

